-- Pre-release baseline generated from the final schema produced by the legacy migration chain.
-- Add all post-release schema changes as new migrations; do not edit this file in place.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "public"."AcpSupport" AS ENUM ('full', 'partial', 'none');

-- CreateEnum
CREATE TYPE "public"."ActivityState" AS ENUM ('thinking', 'tool_call', 'awaiting_permission', 'idle');

-- CreateEnum
CREATE TYPE "public"."AgentCallPolicy" AS ENUM ('all', 'selected');

-- CreateEnum
CREATE TYPE "public"."AgentStatus" AS ENUM ('active', 'inactive', 'paused');

-- CreateEnum
CREATE TYPE "public"."AssignmentState" AS ENUM ('active', 'draining', 'released', 'frozen');

-- CreateEnum
CREATE TYPE "public"."AuditKind" AS ENUM ('daemon_auth', 'daemon_register', 'daemon_unreachable', 'route_assign', 'route_release', 'drain', 'agent_launch', 'agent_stop', 'scope_denied', 'secret_grant', 'secret_revoke', 'cron_change', 'protocol_error', 'api_key_create', 'api_key_rotate', 'api_key_revoke', 'hook_change', 'agent_repo_change', 'mcp_tool_call', 'org_invite_change');

-- CreateEnum
CREATE TYPE "public"."ChannelTrigger" AS ENUM ('off', 'mention', 'any');

-- CreateEnum
CREATE TYPE "public"."ConversationKind" AS ENUM ('channel', 'im', 'mpim');

-- CreateEnum
CREATE TYPE "public"."CronRunStatus" AS ENUM ('running', 'success', 'failed');

-- CreateEnum
CREATE TYPE "public"."DaemonLifecycleOpStatus" AS ENUM ('pending', 'succeeded', 'failed');

-- CreateEnum
CREATE TYPE "public"."DaemonLifecycleOpType" AS ENUM ('restart', 'upgrade');

-- CreateEnum
CREATE TYPE "public"."DaemonStatus" AS ENUM ('provisioned', 'authenticating', 'ready', 'draining', 'unreachable', 'disabled');

-- CreateEnum
CREATE TYPE "public"."ExternalAccessPolicyState" AS ENUM ('disabled', 'enabling', 'enabled', 'degraded');

-- CreateEnum
CREATE TYPE "public"."ExternalMemoryConnectionStatus" AS ENUM ('probing', 'ready', 'degraded', 'invalid');

-- CreateEnum
CREATE TYPE "public"."ExternalResolution" AS ENUM ('pending', 'settled', 'invalid');

-- CreateEnum
CREATE TYPE "public"."FeishuAppRegistrationStatus" AS ENUM ('pending', 'authorized', 'completed', 'failed');

-- CreateEnum
CREATE TYPE "public"."GitAccess" AS ENUM ('read', 'write');

-- CreateEnum
CREATE TYPE "public"."HealthState" AS ENUM ('ok', 'degraded');

-- CreateEnum
CREATE TYPE "public"."HookGateMode" AS ENUM ('informational', 'required');

-- CreateEnum
CREATE TYPE "public"."HookKind" AS ENUM ('webhook', 'github');

-- CreateEnum
CREATE TYPE "public"."HookReportingMode" AS ENUM ('off', 'check', 'status');

-- CreateEnum
CREATE TYPE "public"."HookReviewPolicy" AS ENUM ('off', 'comment', 'request_changes', 'full');

-- CreateEnum
CREATE TYPE "public"."HookSessionMode" AS ENUM ('perDelivery', 'perThread', 'shared');

-- CreateEnum
CREATE TYPE "public"."IntegrationStatus" AS ENUM ('active', 'revoked');

-- CreateEnum
CREATE TYPE "public"."LaunchMode" AS ENUM ('long_lived', 'per_turn');

-- CreateEnum
CREATE TYPE "public"."LaunchStatus" AS ENUM ('launching', 'running', 'stopped', 'crashed');

-- CreateEnum
CREATE TYPE "public"."LeaseStatus" AS ENUM ('active', 'expired', 'revoked');

-- CreateEnum
CREATE TYPE "public"."McpProviderKind" AS ENUM ('custom', 'open_connector');

-- CreateEnum
CREATE TYPE "public"."McpTransport" AS ENUM ('http', 'sse');

-- CreateEnum
CREATE TYPE "public"."MemoryPluginTransport" AS ENUM ('streamable_http', 'stdio');

-- CreateEnum
CREATE TYPE "public"."OrgRole" AS ENUM ('owner', 'collaborator', 'viewer');

-- CreateEnum
CREATE TYPE "public"."OrganizationArtifactSource" AS ENUM ('manual', 'dream');

-- CreateEnum
CREATE TYPE "public"."OrganizationEnvironmentAudience" AS ENUM ('all', 'selected');

-- CreateEnum
CREATE TYPE "public"."OrganizationEnvironmentKind" AS ENUM ('variable', 'secret');

-- CreateEnum
CREATE TYPE "public"."OrganizationSuggestionKind" AS ENUM ('knowledge', 'skill');

-- CreateEnum
CREATE TYPE "public"."OrganizationSuggestionOperation" AS ENUM ('create', 'update');

-- CreateEnum
CREATE TYPE "public"."OrganizationSuggestionState" AS ENUM ('pending', 'accepted', 'rejected');

-- CreateEnum
CREATE TYPE "public"."PresetAgentKind" AS ENUM ('general');

-- CreateEnum
CREATE TYPE "public"."PresetAgentState" AS ENUM ('created', 'skipped');

-- CreateEnum
CREATE TYPE "public"."PrincipalType" AS ENUM ('daemon', 'user', 'relay', 'oauth');

-- CreateEnum
CREATE TYPE "public"."RepoAccess" AS ENUM ('read', 'comment', 'write');

-- CreateEnum
CREATE TYPE "public"."ResourceVisibility" AS ENUM ('org', 'restricted');

-- CreateEnum
CREATE TYPE "public"."SessionPhase" AS ENUM ('start', 'plan', 'problem', 'end');

-- CreateEnum
CREATE TYPE "public"."SessionVisibility" AS ENUM ('private', 'org', 'external');

-- CreateEnum
CREATE TYPE "public"."SlackPlatformInstallStatus" AS ENUM ('pending', 'completed', 'failed');

-- CreateEnum
CREATE TYPE "public"."SlackTransport" AS ENUM ('socket', 'http');

-- CreateEnum
CREATE TYPE "public"."VisibilitySource" AS ENUM ('default', 'inherited_pending', 'inherited', 'explicit');

-- CreateEnum
CREATE TYPE "public"."WaitlistStatus" AS ENUM ('pending', 'approved', 'rejected');

-- CreateEnum
CREATE TYPE "public"."WebchatMcpGrantStatus" AS ENUM ('pending', 'active', 'revoked', 'expired');

-- CreateEnum
CREATE TYPE "public"."WebchatMcpOperationStatus" AS ENUM ('awaiting_confirmation', 'executing', 'completed', 'failed', 'ambiguous', 'stale');

-- CreateEnum
CREATE TYPE "public"."WorkspaceIsolation" AS ENUM ('shared', 'session');

-- CreateEnum
CREATE TYPE "public"."WorkspaceMode" AS ENUM ('scratch', 'github');

-- CreateTable
CREATE TABLE "public"."agent" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "runtime" TEXT,
    "status" "public"."AgentStatus" NOT NULL DEFAULT 'inactive',
    "daemonId" UUID,
    "capabilities" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "permissions" JSONB NOT NULL DEFAULT '{}',
    "runtimeOverrides" JSONB,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "description" TEXT,
    "workspaceMode" "public"."WorkspaceMode" NOT NULL DEFAULT 'scratch',
    "gitRepo" TEXT,
    "gitBranch" TEXT DEFAULT 'main',
    "agentDir" TEXT,
    "createdByUserId" TEXT,
    "displayName" TEXT,
    "lastModifiedByUserId" TEXT,
    "lastModifiedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "visibility" "public"."ResourceVisibility" NOT NULL DEFAULT 'org',
    "sharedWith" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "installationId" TEXT,
    "gitAccess" "public"."GitAccess" NOT NULL DEFAULT 'write',
    "callPolicy" "public"."AgentCallPolicy" NOT NULL DEFAULT 'all',
    "allowedCallerAgentIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "workspaceRepoId" BIGINT,
    "icon" JSONB,
    "introduceOnJoin" BOOLEAN NOT NULL DEFAULT false,
    "runInSandbox" BOOLEAN NOT NULL DEFAULT false,
    "outboundPolicy" "public"."AgentCallPolicy" NOT NULL DEFAULT 'all',
    "allowedTargetAgentIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "managedSkills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "workspaceIsolation" "public"."WorkspaceIsolation" NOT NULL DEFAULT 'shared',
    "configRevision" BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT "agent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."agent_launch" (
    "id" UUID NOT NULL,
    "agentId" UUID NOT NULL,
    "daemonId" UUID NOT NULL,
    "runtime" TEXT NOT NULL,
    "mode" "public"."LaunchMode" NOT NULL DEFAULT 'long_lived',
    "acpSessionId" TEXT,
    "activeCapabilities" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "status" "public"."LaunchStatus" NOT NULL DEFAULT 'launching',
    "launchEpoch" BIGINT NOT NULL,
    "startedAt" TIMESTAMPTZ(6),
    "stoppedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "correlationId" UUID,
    "createdByUserId" TEXT,

    CONSTRAINT "agent_launch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."agent_repo_authorization" (
    "id" UUID NOT NULL,
    "agentId" UUID NOT NULL,
    "repoId" BIGINT NOT NULL,
    "repoFullName" TEXT NOT NULL,
    "access" "public"."RepoAccess" NOT NULL,
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "agent_repo_authorization_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."agent_secret" (
    "agentId" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "agent_secret_pkey" PRIMARY KEY ("agentId","key")
);

-- CreateTable
CREATE TABLE "public"."api_key" (
    "id" TEXT NOT NULL,
    "principalType" "public"."PrincipalType" NOT NULL,
    "orgId" TEXT,
    "daemonId" UUID,
    "userId" TEXT,
    "hash" TEXT NOT NULL,
    "displayTail" TEXT NOT NULL,
    "name" TEXT,
    "scopes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastUsedAt" TIMESTAMPTZ(6),
    "expiresAt" TIMESTAMPTZ(6),
    "revokedAt" TIMESTAMPTZ(6),
    "revokedReason" TEXT,
    "oauthGrantId" TEXT,

    CONSTRAINT "api_key_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."app_user" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "displayName" TEXT,
    "oidcSubject" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "picture" TEXT,
    "profilePictureUpdatedAt" TIMESTAMPTZ(6),
    "activatedAt" TIMESTAMPTZ(6),

    CONSTRAINT "app_user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."assignment" (
    "id" TEXT NOT NULL,
    "platform" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "thread" TEXT,
    "agentId" UUID NOT NULL,
    "daemonId" UUID,
    "workspaceId" TEXT NOT NULL,
    "assignedEpoch" BIGINT NOT NULL,
    "assignedSeq" BIGINT,
    "routingEpoch" BIGINT NOT NULL,
    "state" "public"."AssignmentState" NOT NULL DEFAULT 'active',
    "bindRules" JSONB NOT NULL DEFAULT '[]',
    "releasedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "threadKey" TEXT GENERATED ALWAYS AS (COALESCE("thread", '')) STORED NOT NULL,

    CONSTRAINT "assignment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."audit_event" (
    "id" BIGSERIAL NOT NULL,
    "orgId" TEXT,
    "kind" "public"."AuditKind" NOT NULL,
    "daemonId" UUID,
    "agentId" UUID,
    "sessionId" UUID,
    "actorUserId" TEXT,
    "frameType" TEXT,
    "frameCorr" UUID,
    "message" TEXT,
    "details" JSONB,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."bot" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "platform" TEXT NOT NULL DEFAULT 'slack',
    "name" TEXT NOT NULL,
    "prebuilt" BOOLEAN NOT NULL DEFAULT false,
    "createdByUserId" TEXT,
    "lastUsedAt" TIMESTAMPTZ(6),
    "lastAgentName" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "slackAppId" TEXT,
    "shareable" BOOLEAN NOT NULL DEFAULT false,
    "discordAppId" TEXT,
    "transport" "public"."SlackTransport" NOT NULL DEFAULT 'socket',
    "feishuRegion" TEXT,
    "teamId" TEXT,
    "botUserId" TEXT,
    "revokedAt" TIMESTAMPTZ(6),
    "credentialRevision" INTEGER NOT NULL DEFAULT 1,
    "credentialInstalledAt" TIMESTAMPTZ(6),
    "feishuAppId" TEXT,
    "workspaceId" TEXT,
    "workspaceName" TEXT,
    "externalAppId" TEXT,
    "externalTenantId" TEXT,
    "platformConfig" JSONB,

    CONSTRAINT "bot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."bot_secret" (
    "botId" UUID NOT NULL,
    "botToken" TEXT NOT NULL,
    "appToken" TEXT,
    "signingSecret" TEXT,
    "verificationToken" TEXT,
    "encryptKey" TEXT,

    CONSTRAINT "bot_secret_pkey" PRIMARY KEY ("botId")
);

-- CreateTable
CREATE TABLE "public"."cron_def" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "agentId" UUID,
    "schedule" TEXT NOT NULL,
    "targetPlatform" TEXT NOT NULL DEFAULT 'slack',
    "targetChannel" TEXT,
    "trigger" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "lastRunAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "targetIntegrationId" UUID,
    "createdByUserId" TEXT,
    "name" TEXT,
    "lastModifiedByUserId" TEXT,
    "lastModifiedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "visibility" "public"."ResourceVisibility" NOT NULL DEFAULT 'org',
    "sharedWith" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "timezone" TEXT NOT NULL,

    CONSTRAINT "cron_def_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."cron_run" (
    "id" TEXT NOT NULL,
    "cronId" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "startedAt" TIMESTAMPTZ(6) NOT NULL,
    "status" "public"."CronRunStatus" NOT NULL DEFAULT 'running',
    "durationMs" INTEGER,
    "sessionId" TEXT,
    "reason" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "cron_run_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."daemon" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "host" TEXT,
    "agentVersion" TEXT,
    "machineId" UUID,
    "tokenFp" TEXT,
    "attestationFp" TEXT,
    "capabilities" JSONB NOT NULL DEFAULT '{}',
    "maxAgents" INTEGER NOT NULL DEFAULT 0,
    "sessionEpoch" BIGINT NOT NULL DEFAULT 0,
    "routingEpoch" BIGINT NOT NULL DEFAULT 0,
    "status" "public"."DaemonStatus" NOT NULL DEFAULT 'provisioned',
    "health" "public"."HealthState" NOT NULL DEFAULT 'ok',
    "load" JSONB,
    "activeSessions" INTEGER NOT NULL DEFAULT 0,
    "degradedScopes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "lastSeenAt" TIMESTAMPTZ(6),
    "unreachableAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "name" TEXT,
    "createdByUserId" TEXT,
    "lastModifiedByUserId" TEXT,
    "lastModifiedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "visibility" "public"."ResourceVisibility" NOT NULL DEFAULT 'org',
    "sharedWith" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "mcpServers" JSONB NOT NULL DEFAULT '[]',
    "runtimesSnapshotSeq" INTEGER,
    "sessionRetention" TEXT NOT NULL DEFAULT '7d',

    CONSTRAINT "daemon_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."daemon_lifecycle_op" (
    "id" TEXT NOT NULL,
    "daemonId" UUID NOT NULL,
    "op" "public"."DaemonLifecycleOpType" NOT NULL,
    "targetVersion" TEXT,
    "initiator" TEXT,
    "status" "public"."DaemonLifecycleOpStatus" NOT NULL DEFAULT 'pending',
    "commandEpoch" BIGINT NOT NULL DEFAULT 0,
    "acceptedAt" TIMESTAMPTZ(6),
    "startedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deadline" TIMESTAMPTZ(6) NOT NULL,
    "outcome" TEXT,
    "settledAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "daemon_lifecycle_op_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."deleted_identity_cutoff" (
    "oidcSubject" TEXT NOT NULL,
    "cutoffAt" TIMESTAMPTZ(6) NOT NULL,
    "expiresAt" TIMESTAMPTZ(6) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "deleted_identity_cutoff_pkey" PRIMARY KEY ("oidcSubject")
);

-- CreateTable
CREATE TABLE "public"."deployment_config" (
    "id" INTEGER NOT NULL,
    "schemaVersion" INTEGER NOT NULL,
    "values" JSONB NOT NULL,
    "revision" INTEGER NOT NULL DEFAULT 1,
    "adminClaimedFor" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "deployment_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."deployment_secret" (
    "deploymentConfigId" INTEGER NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "fingerprint" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "deployment_secret_pkey" PRIMARY KEY ("deploymentConfigId","key")
);

-- CreateTable
CREATE TABLE "public"."external_memory_connection" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "orgId" TEXT NOT NULL,
    "installationId" UUID NOT NULL,
    "config" JSONB NOT NULL DEFAULT '{}',
    "status" "public"."ExternalMemoryConnectionStatus" NOT NULL DEFAULT 'probing',
    "revision" INTEGER NOT NULL DEFAULT 1,
    "probedRevision" INTEGER,
    "pluginVersion" TEXT,
    "profile" TEXT,
    "manifestDigest" TEXT,
    "capabilities" JSONB,
    "declaredEgressHosts" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "reasonCode" TEXT,
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "external_memory_connection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."external_memory_connection_secret" (
    "connectionId" UUID NOT NULL,
    "values" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "external_memory_connection_secret_pkey" PRIMARY KEY ("connectionId")
);

-- CreateTable
CREATE TABLE "public"."external_memory_grant" (
    "id" TEXT NOT NULL,
    "connectionId" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "external_memory_grant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."external_scope" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "orgId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "realmKey" TEXT NOT NULL,
    "resourceKind" TEXT NOT NULL,
    "resourceKey" TEXT NOT NULL,
    "credentialKind" TEXT,
    "credentialId" TEXT,
    "aclRevision" BIGINT NOT NULL DEFAULT 0,
    "revokedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "external_scope_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."feishu_app_registration" (
    "id" UUID NOT NULL,
    "targetKey" TEXT,
    "orgId" TEXT NOT NULL,
    "agentId" UUID NOT NULL,
    "requestedName" TEXT,
    "fallbackRegion" TEXT NOT NULL,
    "authorizationUrl" TEXT NOT NULL,
    "providerDomain" TEXT NOT NULL,
    "deviceCode" TEXT,
    "intervalMs" INTEGER NOT NULL,
    "nextPollAt" TIMESTAMPTZ(6) NOT NULL,
    "expiresAt" TIMESTAMPTZ(6) NOT NULL,
    "status" "public"."FeishuAppRegistrationStatus" NOT NULL DEFAULT 'pending',
    "failureReason" TEXT,
    "appId" TEXT,
    "appSecret" TEXT,
    "resolvedRegion" TEXT,
    "botId" UUID NOT NULL,
    "integrationId" UUID NOT NULL,
    "createdByUserId" TEXT,
    "claimToken" UUID,
    "claimedUntil" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "settledAt" TIMESTAMPTZ(6),
    "transport" "public"."SlackTransport" NOT NULL DEFAULT 'socket',

    CONSTRAINT "feishu_app_registration_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."github_install_state" (
    "nonce" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "expiresAt" TIMESTAMPTZ(6) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "github_install_state_pkey" PRIMARY KEY ("nonce")
);

-- CreateTable
CREATE TABLE "public"."github_installation" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "installationId" BIGINT NOT NULL,
    "accountLogin" TEXT NOT NULL,
    "accountType" TEXT NOT NULL,
    "repositorySelection" TEXT NOT NULL,
    "suspendedAt" TIMESTAMPTZ(6),
    "revokedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "permissions" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "github_installation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."hook_def" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "agentId" UUID,
    "kind" "public"."HookKind" NOT NULL,
    "name" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "sessionMode" "public"."HookSessionMode" NOT NULL,
    "urlToken" TEXT,
    "repoId" BIGINT,
    "repoFullName" TEXT,
    "events" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "labelFilter" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "mentionOnly" BOOLEAN NOT NULL DEFAULT false,
    "targetPlatform" TEXT NOT NULL DEFAULT 'slack',
    "targetChannel" TEXT,
    "targetIntegrationId" UUID,
    "lastFiredAt" TIMESTAMPTZ(6),
    "createdByUserId" TEXT,
    "lastModifiedByUserId" TEXT,
    "lastModifiedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "commentFamilies" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "configRevision" BIGINT NOT NULL DEFAULT 1,
    "dispatchRevision" BIGINT NOT NULL DEFAULT 1,
    "projectionEpoch" BIGINT NOT NULL DEFAULT 1,
    "reviewPolicy" "public"."HookReviewPolicy" NOT NULL DEFAULT 'off',
    "reportingMode" "public"."HookReportingMode" NOT NULL DEFAULT 'off',
    "gateMode" "public"."HookGateMode" NOT NULL DEFAULT 'informational',
    "requiredAcknowledgedAt" TIMESTAMPTZ(6),
    "requiredAcknowledgedByUserId" TEXT,
    "requiredAcknowledgedConfigRevision" BIGINT,
    "githubSessionKey" TEXT,

    CONSTRAINT "hook_def_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."hook_review_projection" (
    "id" UUID NOT NULL,
    "hookId" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "agentId" UUID NOT NULL,
    "lastResolvedInstallationId" BIGINT,
    "repoId" BIGINT NOT NULL,
    "repoFullName" TEXT NOT NULL,
    "headSha" TEXT NOT NULL,
    "reportSha" TEXT NOT NULL,
    "projectionEpoch" BIGINT NOT NULL,
    "generation" BIGINT NOT NULL DEFAULT 0,
    "currentHookRunId" TEXT,
    "externalId" TEXT NOT NULL,
    "checkRunId" TEXT,
    "mode" "public"."HookReportingMode" NOT NULL,
    "gateMode" "public"."HookGateMode" NOT NULL,
    "desiredState" TEXT NOT NULL,
    "observedState" TEXT,
    "sealedThrough" BIGINT NOT NULL DEFAULT 0,
    "subjectSyncGeneration" BIGINT NOT NULL DEFAULT 0,
    "subjectSyncErrorCode" TEXT,
    "leaseOwner" TEXT,
    "leaseUntil" TIMESTAMPTZ(6),
    "nextAttemptAt" TIMESTAMPTZ(6),
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "lastErrorCode" TEXT,
    "pendingIntent" JSONB,
    "writeMarker" TEXT,
    "writePhase" TEXT,
    "writeStartedAt" TIMESTAMPTZ(6),
    "tombstonedAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "agentName" TEXT,

    CONSTRAINT "hook_review_projection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."hook_review_subject" (
    "projectionId" UUID NOT NULL,
    "pullNumber" INTEGER NOT NULL,
    "headSha" TEXT NOT NULL,
    "baseSha" TEXT,
    "isOpen" BOOLEAN NOT NULL DEFAULT true,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "hook_review_subject_pkey" PRIMARY KEY ("projectionId","pullNumber")
);

-- CreateTable
CREATE TABLE "public"."hook_run" (
    "id" TEXT NOT NULL,
    "hookId" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "deliveryKey" TEXT NOT NULL,
    "event" TEXT,
    "startedAt" TIMESTAMPTZ(6) NOT NULL,
    "status" "public"."CronRunStatus" NOT NULL DEFAULT 'running',
    "durationMs" INTEGER,
    "sessionId" TEXT,
    "reason" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "agentId" UUID,
    "configRevision" BIGINT,
    "dispatchRevision" BIGINT,
    "projectionEpoch" BIGINT,
    "dispatchDaemonId" UUID,
    "reviewPolicySnapshot" "public"."HookReviewPolicy",
    "reportingModeSnapshot" "public"."HookReportingMode",
    "gateModeSnapshot" "public"."HookGateMode",
    "projectionIntent" TEXT,
    "repoId" BIGINT,
    "repoFullName" TEXT,
    "sourceInstallationId" BIGINT,
    "subjectKind" TEXT,
    "pullNumber" INTEGER,
    "headSha" TEXT,
    "baseSha" TEXT,
    "reportSha" TEXT,
    "isDraft" BOOLEAN,
    "baseChanged" BOOLEAN,
    "turnStartedAt" TIMESTAMPTZ(6),
    "completedAt" TIMESTAMPTZ(6),
    "orphanedAt" TIMESTAMPTZ(6),
    "projectionId" UUID,
    "projectionGeneration" BIGINT,
    "reviewAttemptId" UUID,
    "reviewAttemptState" TEXT,
    "reviewErrorCode" TEXT,
    "reviewId" TEXT,
    "reviewEvent" TEXT,
    "verdict" TEXT,
    "reviewCommitId" TEXT,
    "redeliveryAttempts" INTEGER NOT NULL DEFAULT 0,
    "redeliveryLastRequestedAt" TIMESTAMPTZ(6),
    "redeliveryNextAttemptAt" TIMESTAMPTZ(6),
    "publishedCommentKind" TEXT,
    "publishedCommentId" TEXT,

    CONSTRAINT "hook_run_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."hook_secret" (
    "hookId" UUID NOT NULL,
    "hmacSecret" TEXT NOT NULL,

    CONSTRAINT "hook_secret_pkey" PRIMARY KEY ("hookId")
);

-- CreateTable
CREATE TABLE "public"."integration" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "agentId" UUID NOT NULL,
    "platform" TEXT NOT NULL DEFAULT 'slack',
    "name" TEXT NOT NULL,
    "status" "public"."IntegrationStatus" NOT NULL DEFAULT 'active',
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "botId" UUID NOT NULL,
    "feishuRegion" TEXT,
    "revokedCredentialRevision" INTEGER,

    CONSTRAINT "integration_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."integration_channel" (
    "integrationId" UUID NOT NULL,
    "channelId" TEXT NOT NULL,
    "name" TEXT,
    "isPrivate" BOOLEAN NOT NULL DEFAULT false,
    "trigger" "public"."ChannelTrigger" NOT NULL DEFAULT 'mention',
    "firstSeenAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "agentId" UUID,
    "kind" "public"."ConversationKind" NOT NULL DEFAULT 'channel',
    "spaceId" TEXT,
    "space" TEXT,

    CONSTRAINT "integration_channel_pkey" PRIMARY KEY ("integrationId","channelId")
);

-- CreateTable
CREATE TABLE "public"."managed_skill" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "orgId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "currentRevision" INTEGER NOT NULL DEFAULT 1,
    "archivedAt" TIMESTAMPTZ(6),
    "archivedByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "managed_skill_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."managed_skill_revision" (
    "managedSkillId" UUID NOT NULL,
    "revision" INTEGER NOT NULL,
    "archive" BYTEA NOT NULL,
    "digest" TEXT NOT NULL,
    "compressedBytes" INTEGER NOT NULL,
    "expandedBytes" INTEGER NOT NULL,
    "fileCount" INTEGER NOT NULL,
    "manifest" JSONB NOT NULL,
    "source" "public"."OrganizationArtifactSource" NOT NULL,
    "sourceAgentId" UUID,
    "sourceDreamId" TEXT,
    "sourceCandidateId" UUID,
    "sourceSessionIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "createdByUserId" TEXT,
    "reviewedByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "managed_skill_revision_pkey" PRIMARY KEY ("managedSkillId","revision")
);

-- CreateTable
CREATE TABLE "public"."mcp_grant" (
    "id" TEXT NOT NULL,
    "mcpProviderId" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mcp_grant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."mcp_provider" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "transport" "public"."McpTransport" NOT NULL DEFAULT 'http',
    "url" TEXT NOT NULL,
    "visibility" "public"."ResourceVisibility" NOT NULL DEFAULT 'org',
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "sharedWith" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "kind" "public"."McpProviderKind" NOT NULL DEFAULT 'custom',

    CONSTRAINT "mcp_provider_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."mcp_provider_secret" (
    "mcpProviderId" UUID NOT NULL,
    "headers" JSONB NOT NULL DEFAULT '[]',

    CONSTRAINT "mcp_provider_secret_pkey" PRIMARY KEY ("mcpProviderId")
);

-- CreateTable
CREATE TABLE "public"."membership" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "role" "public"."OrgRole" NOT NULL DEFAULT 'collaborator',
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
    "lastSelectedAt" TIMESTAMPTZ(6),

    CONSTRAINT "membership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."memory_plugin_installation" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "orgId" TEXT NOT NULL,
    "pluginId" TEXT NOT NULL,
    "transport" "public"."MemoryPluginTransport" NOT NULL DEFAULT 'streamable_http',
    "endpoint" TEXT,
    "commandRef" TEXT,
    "pinnedProfileMajor" INTEGER NOT NULL DEFAULT 1,
    "expectedManifestDigest" TEXT,
    "secretHeaders" JSONB NOT NULL DEFAULT '[]',
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "memory_plugin_installation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."oauth_client" (
    "clientId" TEXT NOT NULL,
    "clientName" TEXT,
    "redirectUris" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "grantTypes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
    "expiresAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "oauth_client_pkey" PRIMARY KEY ("clientId")
);

-- CreateTable
CREATE TABLE "public"."oauth_code" (
    "codeHash" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "redirectUri" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "scopes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "codeChallenge" TEXT NOT NULL,
    "codeChallengeMethod" TEXT NOT NULL,
    "resource" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
    "expiresAt" TIMESTAMPTZ(6) NOT NULL,
    "consumedAt" TIMESTAMPTZ(6),

    CONSTRAINT "oauth_code_pkey" PRIMARY KEY ("codeHash")
);

-- CreateTable
CREATE TABLE "public"."oauth_grant" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "scopes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "resource" TEXT,
    "rtHash" TEXT,
    "prevRtHash" TEXT,
    "rtExpiresAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
    "lastUsedAt" TIMESTAMPTZ(6),
    "revokedAt" TIMESTAMPTZ(6),

    CONSTRAINT "oauth_grant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."org" (
    "id" TEXT NOT NULL,
    "name" TEXT,
    "slug" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "icon" JSONB,
    "defaultAgentVisibility" "public"."AgentCallPolicy" NOT NULL DEFAULT 'all',

    CONSTRAINT "org_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."org_invite_link" (
    "id" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "displayTail" TEXT NOT NULL,
    "expiresAt" TIMESTAMPTZ(6) NOT NULL,
    "revokedAt" TIMESTAMPTZ(6),
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "org_invite_link_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."org_invite_redemption" (
    "inviteLinkId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "redeemedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "org_invite_redemption_pkey" PRIMARY KEY ("inviteLinkId","userId")
);

-- CreateTable
CREATE TABLE "public"."organization_environment_assignment" (
    "orgId" TEXT NOT NULL,
    "entryId" UUID NOT NULL,
    "agentId" UUID NOT NULL,
    "authorizedByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "organization_environment_assignment_pkey" PRIMARY KEY ("entryId","agentId")
);

-- CreateTable
CREATE TABLE "public"."organization_environment_entry" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "orgId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "kind" "public"."OrganizationEnvironmentKind" NOT NULL,
    "variableValue" TEXT,
    "audience" "public"."OrganizationEnvironmentAudience" NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "createdByUserId" TEXT,
    "lastModifiedByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "organization_environment_entry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."organization_environment_secret" (
    "entryId" UUID NOT NULL,
    "value" TEXT NOT NULL,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "organization_environment_secret_pkey" PRIMARY KEY ("entryId")
);

-- CreateTable
CREATE TABLE "public"."organization_knowledge" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "orgId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "currentRevision" INTEGER NOT NULL DEFAULT 1,
    "archivedAt" TIMESTAMPTZ(6),
    "archivedByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "organization_knowledge_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."organization_knowledge_revision" (
    "knowledgeId" UUID NOT NULL,
    "revision" INTEGER NOT NULL,
    "content" TEXT NOT NULL,
    "summary" TEXT,
    "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "digest" TEXT NOT NULL,
    "source" "public"."OrganizationArtifactSource" NOT NULL,
    "sourceAgentId" UUID,
    "sourceDreamId" TEXT,
    "sourceCandidateId" UUID,
    "sourceSessionIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "createdByUserId" TEXT,
    "reviewedByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "organization_knowledge_revision_pkey" PRIMARY KEY ("knowledgeId","revision")
);

-- CreateTable
CREATE TABLE "public"."organization_suggestion" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "orgId" TEXT NOT NULL,
    "sourceAgentId" UUID NOT NULL,
    "sourceDaemonId" UUID,
    "dreamId" TEXT NOT NULL,
    "candidateId" UUID NOT NULL,
    "kind" "public"."OrganizationSuggestionKind" NOT NULL,
    "operation" "public"."OrganizationSuggestionOperation" NOT NULL,
    "targetArtifactId" UUID,
    "targetRevision" INTEGER,
    "title" TEXT NOT NULL,
    "summary" TEXT,
    "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "digest" TEXT NOT NULL,
    "contentBytes" INTEGER NOT NULL,
    "sessionIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "state" "public"."OrganizationSuggestionState" NOT NULL DEFAULT 'pending',
    "reviewedByUserId" TEXT,
    "reviewedAt" TIMESTAMPTZ(6),
    "reviewReason" TEXT,
    "acceptedArtifactId" UUID,
    "acceptedArtifactRevision" INTEGER,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "organization_suggestion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."pending_key_shred" (
    "orgId" TEXT NOT NULL,
    "mount" TEXT NOT NULL,
    "keyName" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "pending_key_shred_pkey" PRIMARY KEY ("orgId")
);

-- CreateTable
CREATE TABLE "public"."preset_agent" (
    "orgId" TEXT NOT NULL,
    "preset" "public"."PresetAgentKind" NOT NULL,
    "agentId" UUID,
    "status" "public"."PresetAgentState" NOT NULL,
    "placementSettledAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "preset_agent_pkey" PRIMARY KEY ("orgId","preset")
);

-- CreateTable
CREATE TABLE "public"."relay" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "daemonUrl" TEXT NOT NULL,
    "lastSeenAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "relay_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."runtime_profile" (
    "id" TEXT NOT NULL,
    "daemonId" UUID NOT NULL,
    "runtime" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "models" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "contextWindow" INTEGER,
    "acpSupport" "public"."AcpSupport" NOT NULL DEFAULT 'none',
    "toolCalling" BOOLEAN NOT NULL DEFAULT false,
    "observedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "acpProtocolVersion" INTEGER,
    "mcpCapabilities" JSONB,
    "modelCatalog" JSONB,
    "modelsSource" TEXT,
    "authRequired" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "runtime_profile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."secret_lease" (
    "id" UUID NOT NULL,
    "daemonId" UUID NOT NULL,
    "scopePlatform" TEXT NOT NULL,
    "scopeWorkspaceId" UUID NOT NULL,
    "ref" TEXT NOT NULL,
    "ttlSec" INTEGER NOT NULL,
    "renewBeforeSec" INTEGER NOT NULL DEFAULT 60,
    "status" "public"."LeaseStatus" NOT NULL DEFAULT 'active',
    "issuedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "renewedAt" TIMESTAMPTZ(6),
    "expiresAt" TIMESTAMPTZ(6) NOT NULL,
    "revokedReason" TEXT,

    CONSTRAINT "secret_lease_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."session_external_access_policy" (
    "orgId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "state" "public"."ExternalAccessPolicyState" NOT NULL DEFAULT 'disabled',
    "currentRev" BIGINT NOT NULL DEFAULT 0,
    "readFenceRev" BIGINT,
    "migrationCursor" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "session_external_access_policy_pkey" PRIMARY KEY ("orgId","provider")
);

-- CreateTable
CREATE TABLE "public"."session_meta" (
    "id" TEXT NOT NULL,
    "agentId" UUID NOT NULL,
    "launchId" UUID,
    "platform" TEXT,
    "channel" TEXT,
    "thread" TEXT,
    "phase" "public"."SessionPhase" NOT NULL DEFAULT 'start',
    "link" TEXT,
    "summary" TEXT,
    "activityState" "public"."ActivityState" NOT NULL DEFAULT 'idle',
    "lastActivityAt" TIMESTAMPTZ(3) NOT NULL,
    "startedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endedAt" TIMESTAMPTZ(6),
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "title" TEXT,
    "status" TEXT,
    "triggeredBy" TEXT,
    "channelName" TEXT,
    "triggeredByName" TEXT,
    "threadUrl" TEXT,
    "runtime" TEXT,
    "model" TEXT,
    "effort" TEXT,
    "fastMode" BOOLEAN,
    "permissionMode" TEXT,
    "outputMode" TEXT,
    "daemonId" UUID,
    "parentSessionId" TEXT,
    "orgId" TEXT NOT NULL,
    "visibility" "public"."SessionVisibility" NOT NULL DEFAULT 'org',
    "ownerIdentity" TEXT,
    "visibilitySource" "public"."VisibilitySource" NOT NULL DEFAULT 'default',
    "visibilityRev" INTEGER NOT NULL DEFAULT 0,
    "visibilityAckedRev" INTEGER NOT NULL DEFAULT -1,
    "externalProvider" TEXT,
    "externalScopeId" UUID,
    "externalResolution" "public"."ExternalResolution",
    "classifiedPolicyRev" BIGINT,
    "legacyUnresolved" BOOLEAN NOT NULL DEFAULT false,
    "tenantScope" TEXT,
    "contentPurgedAt" TIMESTAMPTZ(6),
    "contentPurgedReason" TEXT,
    "workspaceIsolation" "public"."WorkspaceIsolation",

    CONSTRAINT "session_meta_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."session_spend" (
    "agentId" UUID NOT NULL,
    "sessionId" TEXT NOT NULL,
    "at" TIMESTAMPTZ(6) NOT NULL,
    "cumulativeCost" DOUBLE PRECISION NOT NULL,
    "model" TEXT,
    "cumulativeTotalTokens" INTEGER NOT NULL DEFAULT 0,
    "cumulativeInputTokens" INTEGER NOT NULL DEFAULT 0,
    "cumulativeOutputTokens" INTEGER NOT NULL DEFAULT 0,
    "cumulativeThoughtTokens" INTEGER NOT NULL DEFAULT 0,
    "cumulativeCachedReadTokens" INTEGER NOT NULL DEFAULT 0,
    "cumulativeCachedWriteTokens" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "session_spend_pkey" PRIMARY KEY ("agentId","sessionId","at")
);

-- CreateTable
CREATE TABLE "public"."session_usage" (
    "agentId" UUID NOT NULL,
    "sessionId" TEXT NOT NULL,
    "platform" TEXT,
    "channel" TEXT,
    "totalTokens" INTEGER NOT NULL DEFAULT 0,
    "inputTokens" INTEGER NOT NULL DEFAULT 0,
    "outputTokens" INTEGER NOT NULL DEFAULT 0,
    "thoughtTokens" INTEGER NOT NULL DEFAULT 0,
    "cachedReadTokens" INTEGER NOT NULL DEFAULT 0,
    "cachedWriteTokens" INTEGER NOT NULL DEFAULT 0,
    "contextUsed" INTEGER,
    "contextSize" INTEGER,
    "costAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "costCurrency" TEXT,
    "startedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastActivityAt" TIMESTAMPTZ(6) NOT NULL,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "session_usage_pkey" PRIMARY KEY ("agentId","sessionId")
);

-- CreateTable
CREATE TABLE "public"."shared_thread_agent" (
    "botId" UUID NOT NULL,
    "sessionKey" TEXT NOT NULL,
    "agentId" UUID NOT NULL,
    "daemonId" UUID NOT NULL,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "shared_thread_agent_pkey" PRIMARY KEY ("botId","sessionKey")
);

-- CreateTable
CREATE TABLE "public"."shared_thread_participant" (
    "botId" UUID NOT NULL,
    "sessionKey" TEXT NOT NULL,
    "agentId" UUID NOT NULL,
    "daemonId" UUID NOT NULL,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "shared_thread_participant_pkey" PRIMARY KEY ("botId","sessionKey","agentId")
);

-- CreateTable
CREATE TABLE "public"."skill_source" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "githubRepoId" BIGINT,
    "ref" TEXT,
    "subDir" TEXT,
    "skills" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "visibility" "public"."ResourceVisibility" NOT NULL DEFAULT 'org',
    "sharedWith" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "skill_source_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."slack_install" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "agentId" UUID NOT NULL,
    "appId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "clientSecret" TEXT NOT NULL,
    "botToken" TEXT,
    "name" TEXT,
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "transport" "public"."SlackTransport" NOT NULL DEFAULT 'socket',
    "signingSecret" TEXT,

    CONSTRAINT "slack_install_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."slack_platform_install" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "agentId" UUID,
    "status" "public"."SlackPlatformInstallStatus" NOT NULL DEFAULT 'pending',
    "failureReason" TEXT,
    "botId" UUID,
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "settledAt" TIMESTAMPTZ(6),

    CONSTRAINT "slack_platform_install_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."slack_user_config" (
    "orgId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "accessToken" TEXT NOT NULL,
    "refreshToken" TEXT,
    "accessExpiresAt" TIMESTAMPTZ(6) NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "slack_user_config_pkey" PRIMARY KEY ("orgId","userId")
);

-- CreateTable
CREATE TABLE "public"."waitlist_entry" (
    "id" TEXT NOT NULL,
    "email" TEXT,
    "status" "public"."WaitlistStatus" NOT NULL DEFAULT 'pending',
    "note" TEXT,
    "source" TEXT,
    "tokenHash" TEXT,
    "displayTail" TEXT,
    "joinExpiresAt" TIMESTAMPTZ(6),
    "revokedAt" TIMESTAMPTZ(6),
    "approvedByUserId" TEXT,
    "approvedAt" TIMESTAMPTZ(6),
    "redeemedByUserId" TEXT,
    "redeemedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,
    "name" TEXT,
    "redeemedEmail" TEXT,

    CONSTRAINT "waitlist_entry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."webchat_conversation" (
    "id" UUID NOT NULL,
    "orgId" TEXT NOT NULL,
    "agentId" UUID NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "delegationGeneration" INTEGER NOT NULL DEFAULT 0,
    "currentSessionId" TEXT,
    "currentSessionRev" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "webchat_conversation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."webchat_conversation_agent" (
    "conversationId" UUID NOT NULL,
    "agentId" UUID NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'member',
    "ord" INTEGER NOT NULL DEFAULT 0,
    "addedByUserId" TEXT NOT NULL,
    "addedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "currentSessionId" TEXT,
    "currentSessionRev" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "webchat_conversation_agent_pkey" PRIMARY KEY ("conversationId","agentId")
);

-- CreateTable
CREATE TABLE "public"."webchat_mcp_access_grant" (
    "id" UUID NOT NULL,
    "authorityId" UUID NOT NULL,
    "descriptorInstanceId" UUID NOT NULL,
    "grantRevision" INTEGER NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "status" "public"."WebchatMcpGrantStatus" NOT NULL DEFAULT 'pending',
    "pendingExpiresAt" TIMESTAMPTZ(6) NOT NULL,
    "expiresAt" TIMESTAMPTZ(6) NOT NULL,
    "activatedAt" TIMESTAMPTZ(6),
    "revokedAt" TIMESTAMPTZ(6),
    "revokedReason" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "webchat_mcp_access_grant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."webchat_mcp_delegation" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "conversationId" UUID NOT NULL,
    "generation" INTEGER NOT NULL,
    "userId" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "agentId" UUID NOT NULL,
    "daemonId" UUID NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMPTZ(6) NOT NULL,
    "revokedAt" TIMESTAMPTZ(6),
    "revokedReason" TEXT,

    CONSTRAINT "webchat_mcp_delegation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."webchat_mcp_operation" (
    "id" UUID NOT NULL,
    "conversationId" UUID NOT NULL,
    "createdAuthorityGeneration" INTEGER NOT NULL,
    "sourceGrantId" UUID NOT NULL,
    "userId" TEXT NOT NULL,
    "toolName" TEXT NOT NULL,
    "canonicalArguments" JSONB NOT NULL,
    "intentHash" TEXT NOT NULL,
    "status" "public"."WebchatMcpOperationStatus" NOT NULL DEFAULT 'awaiting_confirmation',
    "executionAttemptId" UUID,
    "claimedAt" TIMESTAMPTZ(6),
    "recoveryDeadline" TIMESTAMPTZ(6),
    "boundedResponse" BYTEA,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "confirmationExpiresAt" TIMESTAMPTZ(6) NOT NULL,
    "completedAt" TIMESTAMPTZ(6),

    CONSTRAINT "webchat_mcp_operation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."webchat_mcp_transport_receipt" (
    "grantId" UUID NOT NULL,
    "jsonRpcRequestId" TEXT NOT NULL,
    "conversationId" UUID NOT NULL,
    "requestHash" TEXT NOT NULL,
    "operationId" UUID NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "supersededAt" TIMESTAMPTZ(6),

    CONSTRAINT "webchat_mcp_transport_receipt_pkey" PRIMARY KEY ("grantId","jsonRpcRequestId")
);

-- CreateIndex
CREATE INDEX "agent_allowedCallerAgentIds_gin_idx" ON "public"."agent" USING GIN ("allowedCallerAgentIds");

-- CreateIndex
CREATE INDEX "agent_daemonId_idx" ON "public"."agent"("daemonId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "agent_id_orgId_key" ON "public"."agent"("id" ASC, "orgId" ASC);

-- CreateIndex
CREATE INDEX "agent_orgId_idx" ON "public"."agent"("orgId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "agent_orgId_name_key" ON "public"."agent"("orgId" ASC, "name" ASC);

-- CreateIndex
CREATE INDEX "agent_sharedWith_gin_idx" ON "public"."agent" USING GIN ("sharedWith");

-- CreateIndex
CREATE INDEX "agent_launch_agentId_status_idx" ON "public"."agent_launch"("agentId" ASC, "status" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "agent_launch_correlationId_key" ON "public"."agent_launch"("correlationId" ASC);

-- CreateIndex
CREATE INDEX "agent_launch_daemonId_idx" ON "public"."agent_launch"("daemonId" ASC);

-- CreateIndex
CREATE INDEX "agent_repo_authorization_agentId_idx" ON "public"."agent_repo_authorization"("agentId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "agent_repo_authorization_agentId_repoId_key" ON "public"."agent_repo_authorization"("agentId" ASC, "repoId" ASC);

-- CreateIndex
CREATE INDEX "api_key_daemonId_idx" ON "public"."api_key"("daemonId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "api_key_hash_key" ON "public"."api_key"("hash" ASC);

-- CreateIndex
CREATE INDEX "api_key_oauthGrantId_idx" ON "public"."api_key"("oauthGrantId" ASC);

-- CreateIndex
CREATE INDEX "api_key_orgId_revokedAt_idx" ON "public"."api_key"("orgId" ASC, "revokedAt" ASC);

-- CreateIndex
CREATE INDEX "api_key_userId_idx" ON "public"."api_key"("userId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "app_user_email_key" ON "public"."app_user"("email" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "app_user_oidcSubject_key" ON "public"."app_user"("oidcSubject" ASC);

-- CreateIndex
CREATE INDEX "assignment_agentId_idx" ON "public"."assignment"("agentId" ASC);

-- CreateIndex
CREATE INDEX "assignment_daemonId_state_idx" ON "public"."assignment"("daemonId" ASC, "state" ASC);

-- CreateIndex
CREATE INDEX "assignment_platform_channel_threadKey_idx" ON "public"."assignment"("platform" ASC, "channel" ASC, "threadKey" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "assignment_session_active_uq" ON "public"."assignment"("platform" ASC, "channel" ASC, "threadKey" ASC)
WHERE "state" IN ('active', 'draining', 'frozen');

-- CreateIndex
CREATE INDEX "audit_event_daemonId_createdAt_idx" ON "public"."audit_event"("daemonId" ASC, "createdAt" ASC);

-- CreateIndex
CREATE INDEX "audit_event_kind_createdAt_idx" ON "public"."audit_event"("kind" ASC, "createdAt" ASC);

-- CreateIndex
CREATE INDEX "audit_event_orgId_createdAt_idx" ON "public"."audit_event"("orgId" ASC, "createdAt" ASC);

-- CreateIndex
CREATE INDEX "bot_orgId_idx" ON "public"."bot"("orgId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "bot_platform_externalAppId_externalTenantId_key" ON "public"."bot"("platform" ASC, "externalAppId" ASC, "externalTenantId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "bot_slackAppId_teamId_key" ON "public"."bot"("slackAppId" ASC, "teamId" ASC);

-- CreateIndex
CREATE INDEX "cron_def_agentId_idx" ON "public"."cron_def"("agentId" ASC);

-- CreateIndex
CREATE INDEX "cron_def_orgId_idx" ON "public"."cron_def"("orgId" ASC);

-- CreateIndex
CREATE INDEX "cron_def_sharedWith_gin_idx" ON "public"."cron_def" USING GIN ("sharedWith");

-- CreateIndex
CREATE INDEX "cron_def_targetIntegrationId_idx" ON "public"."cron_def"("targetIntegrationId" ASC);

-- CreateIndex
CREATE INDEX "cron_run_cronId_startedAt_idx" ON "public"."cron_run"("cronId" ASC, "startedAt" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "cron_run_cronId_startedAt_key" ON "public"."cron_run"("cronId" ASC, "startedAt" ASC);

-- CreateIndex
CREATE INDEX "daemon_lastSeenAt_idx" ON "public"."daemon"("lastSeenAt" ASC);

-- CreateIndex
CREATE INDEX "daemon_orgId_idx" ON "public"."daemon"("orgId" ASC);

-- CreateIndex
CREATE INDEX "daemon_sharedWith_gin_idx" ON "public"."daemon" USING GIN ("sharedWith");

-- CreateIndex
CREATE INDEX "daemon_status_idx" ON "public"."daemon"("status" ASC);

-- CreateIndex
CREATE INDEX "daemon_lifecycle_op_daemonId_status_idx" ON "public"."daemon_lifecycle_op"("daemonId" ASC, "status" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "daemon_lifecycle_op_daemon_pending_uq" ON "public"."daemon_lifecycle_op"("daemonId" ASC)
WHERE "status" = 'pending';

-- CreateIndex
CREATE INDEX "deleted_identity_cutoff_expiresAt_idx" ON "public"."deleted_identity_cutoff"("expiresAt" ASC);

-- CreateIndex
CREATE INDEX "external_memory_connection_installationId_idx" ON "public"."external_memory_connection"("installationId" ASC);

-- CreateIndex
CREATE INDEX "external_memory_connection_orgId_idx" ON "public"."external_memory_connection"("orgId" ASC);

-- CreateIndex
CREATE INDEX "external_memory_grant_connectionId_idx" ON "public"."external_memory_grant"("connectionId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "external_memory_grant_key_key" ON "public"."external_memory_grant"("key" ASC);

-- CreateIndex
CREATE INDEX "external_scope_credentialKind_credentialId_idx" ON "public"."external_scope"("credentialKind" ASC, "credentialId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "external_scope_id_orgId_provider_key" ON "public"."external_scope"("id" ASC, "orgId" ASC, "provider" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "external_scope_orgId_provider_realmKey_resourceKind_resourceKey" ON "public"."external_scope"("orgId" ASC, "provider" ASC, "realmKey" ASC, "resourceKind" ASC, "resourceKey" ASC);

-- CreateIndex
CREATE INDEX "feishu_app_registration_status_nextPollAt_idx" ON "public"."feishu_app_registration"("status" ASC, "nextPollAt" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "feishu_app_registration_targetKey_key" ON "public"."feishu_app_registration"("targetKey" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "github_installation_installationId_key" ON "public"."github_installation"("installationId" ASC);

-- CreateIndex
CREATE INDEX "github_installation_orgId_idx" ON "public"."github_installation"("orgId" ASC);

-- CreateIndex
CREATE INDEX "hook_def_agentId_idx" ON "public"."hook_def"("agentId" ASC);

-- CreateIndex
CREATE INDEX "hook_def_kind_repoId_idx" ON "public"."hook_def"("kind" ASC, "repoId" ASC);

-- CreateIndex
CREATE INDEX "hook_def_orgId_idx" ON "public"."hook_def"("orgId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "hook_def_urlToken_key" ON "public"."hook_def"("urlToken" ASC);

-- CreateIndex
CREATE INDEX "hook_review_projection_agentId_repoId_idx" ON "public"."hook_review_projection"("agentId" ASC, "repoId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "hook_review_projection_checkRunId_key" ON "public"."hook_review_projection"("checkRunId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "hook_review_projection_externalId_key" ON "public"."hook_review_projection"("externalId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "hook_review_projection_hookId_repoId_reportSha_projectionEpoch_" ON "public"."hook_review_projection"("hookId" ASC, "repoId" ASC, "reportSha" ASC, "projectionEpoch" ASC);

-- CreateIndex
CREATE INDEX "hook_review_projection_lastResolvedInstallationId_idx" ON "public"."hook_review_projection"("lastResolvedInstallationId" ASC);

-- CreateIndex
CREATE INDEX "hook_review_projection_nextAttemptAt_leaseUntil_idx" ON "public"."hook_review_projection"("nextAttemptAt" ASC, "leaseUntil" ASC);

-- CreateIndex
CREATE INDEX "hook_review_projection_orgId_idx" ON "public"."hook_review_projection"("orgId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "hook_review_projection_writeMarker_key" ON "public"."hook_review_projection"("writeMarker" ASC);

-- CreateIndex
CREATE INDEX "hook_review_subject_headSha_idx" ON "public"."hook_review_subject"("headSha" ASC);

-- CreateIndex
CREATE INDEX "hook_run_deliveryKey_status_redeliveryNextAttemptAt_idx" ON "public"."hook_run"("deliveryKey" ASC, "status" ASC, "redeliveryNextAttemptAt" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "hook_run_hookId_deliveryKey_key" ON "public"."hook_run"("hookId" ASC, "deliveryKey" ASC);

-- CreateIndex
CREATE INDEX "hook_run_hookId_repoId_reportSha_startedAt_idx" ON "public"."hook_run"("hookId" ASC, "repoId" ASC, "reportSha" ASC, "startedAt" DESC);

-- CreateIndex
CREATE INDEX "hook_run_hookId_startedAt_idx" ON "public"."hook_run"("hookId" ASC, "startedAt" DESC);

-- CreateIndex
CREATE INDEX "hook_run_orgId_idx" ON "public"."hook_run"("orgId" ASC);

-- CreateIndex
CREATE INDEX "hook_run_projectionId_projectionGeneration_idx" ON "public"."hook_run"("projectionId" ASC, "projectionGeneration" ASC);

-- CreateIndex
CREATE INDEX "hook_run_redelivery_due_idx" ON "public"."hook_run"("status" ASC, "redeliveryNextAttemptAt" ASC, "redeliveryAttempts" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "hook_run_reviewAttemptId_key" ON "public"."hook_run"("reviewAttemptId" ASC);

-- CreateIndex
CREATE INDEX "hook_run_status_startedAt_idx" ON "public"."hook_run"("status" ASC, "startedAt" ASC);

-- CreateIndex
CREATE INDEX "integration_agentId_idx" ON "public"."integration"("agentId" ASC);

-- CreateIndex
CREATE INDEX "integration_botId_idx" ON "public"."integration"("botId" ASC);

-- CreateIndex
CREATE INDEX "integration_orgId_idx" ON "public"."integration"("orgId" ASC);

-- CreateIndex
CREATE INDEX "integration_channel_agentId_idx" ON "public"."integration_channel"("agentId" ASC);

-- CreateIndex
CREATE INDEX "managed_skill_orgId_archivedAt_updatedAt_idx" ON "public"."managed_skill"("orgId" ASC, "archivedAt" ASC, "updatedAt" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "managed_skill_orgId_name_key" ON "public"."managed_skill"("orgId" ASC, "name" ASC);

-- CreateIndex
CREATE INDEX "managed_skill_revision_createdAt_idx" ON "public"."managed_skill_revision"("createdAt" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "mcp_grant_key_key" ON "public"."mcp_grant"("key" ASC);

-- CreateIndex
CREATE INDEX "mcp_grant_mcpProviderId_idx" ON "public"."mcp_grant"("mcpProviderId" ASC);

-- CreateIndex
CREATE INDEX "mcp_provider_orgId_idx" ON "public"."mcp_provider"("orgId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "mcp_provider_orgId_name_key" ON "public"."mcp_provider"("orgId" ASC, "name" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "membership_orgId_userId_key" ON "public"."membership"("orgId" ASC, "userId" ASC);

-- CreateIndex
CREATE INDEX "membership_userId_idx" ON "public"."membership"("userId" ASC);

-- CreateIndex
CREATE INDEX "memory_plugin_installation_orgId_pluginId_idx" ON "public"."memory_plugin_installation"("orgId" ASC, "pluginId" ASC);

-- CreateIndex
CREATE INDEX "oauth_client_expiresAt_idx" ON "public"."oauth_client"("expiresAt" ASC);

-- CreateIndex
CREATE INDEX "oauth_code_expiresAt_idx" ON "public"."oauth_code"("expiresAt" ASC);

-- CreateIndex
CREATE INDEX "oauth_grant_prevRtHash_idx" ON "public"."oauth_grant"("prevRtHash" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "oauth_grant_rtHash_key" ON "public"."oauth_grant"("rtHash" ASC);

-- CreateIndex
CREATE INDEX "oauth_grant_userId_idx" ON "public"."oauth_grant"("userId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "org_slug_key" ON "public"."org"("slug" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "org_invite_link_orgId_key" ON "public"."org_invite_link"("orgId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "org_invite_link_tokenHash_key" ON "public"."org_invite_link"("tokenHash" ASC);

-- CreateIndex
CREATE INDEX "org_invite_redemption_userId_idx" ON "public"."org_invite_redemption"("userId" ASC);

-- CreateIndex
CREATE INDEX "organization_environment_assignment_orgId_agentId_idx" ON "public"."organization_environment_assignment"("orgId" ASC, "agentId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "organization_environment_entry_id_orgId_key" ON "public"."organization_environment_entry"("id" ASC, "orgId" ASC);

-- CreateIndex
CREATE INDEX "organization_environment_entry_orgId_audience_idx" ON "public"."organization_environment_entry"("orgId" ASC, "audience" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "organization_environment_entry_orgId_key_key" ON "public"."organization_environment_entry"("orgId" ASC, "key" ASC);

-- CreateIndex
CREATE INDEX "organization_knowledge_orgId_archivedAt_updatedAt_idx" ON "public"."organization_knowledge"("orgId" ASC, "archivedAt" ASC, "updatedAt" ASC);

-- CreateIndex
CREATE INDEX "organization_knowledge_revision_createdAt_idx" ON "public"."organization_knowledge_revision"("createdAt" ASC);

-- CreateIndex
CREATE INDEX "organization_suggestion_orgId_state_createdAt_idx" ON "public"."organization_suggestion"("orgId" ASC, "state" ASC, "createdAt" ASC);

-- CreateIndex
CREATE INDEX "organization_suggestion_sourceDaemonId_state_idx" ON "public"."organization_suggestion"("sourceDaemonId" ASC, "state" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "organization_suggestion_source_key" ON "public"."organization_suggestion"("sourceAgentId" ASC, "dreamId" ASC, "candidateId" ASC);

-- CreateIndex
CREATE INDEX "preset_agent_agentId_idx" ON "public"."preset_agent"("agentId" ASC);

-- CreateIndex
CREATE INDEX "relay_lastSeenAt_idx" ON "public"."relay"("lastSeenAt" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "relay_name_key" ON "public"."relay"("name" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "runtime_profile_daemonId_runtime_key" ON "public"."runtime_profile"("daemonId" ASC, "runtime" ASC);

-- CreateIndex
CREATE INDEX "secret_lease_daemonId_status_idx" ON "public"."secret_lease"("daemonId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "secret_lease_status_expiresAt_idx" ON "public"."secret_lease"("status" ASC, "expiresAt" ASC);

-- CreateIndex
CREATE INDEX "session_meta_activity_page_idx" ON "public"."session_meta"("lastActivityAt" DESC, "startedAt" DESC, "id" DESC, "agentId" ASC);

-- CreateIndex
CREATE INDEX "session_meta_agentId_startedAt_idx" ON "public"."session_meta"("agentId" ASC, "startedAt" ASC);

-- CreateIndex
CREATE INDEX "session_meta_agent_activity_page_idx" ON "public"."session_meta"("agentId" ASC, "lastActivityAt" DESC, "startedAt" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "session_meta_agent_channel_page_idx" ON "public"."session_meta"("agentId" ASC, "channel" ASC, "lastActivityAt" DESC, "startedAt" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "session_meta_agent_platform_page_idx" ON "public"."session_meta"("agentId" ASC, "platform" ASC, "lastActivityAt" DESC, "startedAt" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "session_meta_agent_trigger_page_idx" ON "public"."session_meta"("agentId" ASC, "triggeredBy" ASC, "lastActivityAt" DESC, "startedAt" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "session_meta_conversation_key_idx" ON "public"."session_meta"("orgId" ASC, "platform" ASC, "tenantScope" ASC, "channel" ASC, "thread" ASC, "lastActivityAt" DESC, "startedAt" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "session_meta_daemonId_idx" ON "public"."session_meta"("daemonId" ASC);

-- CreateIndex
CREATE INDEX "session_meta_launchId_idx" ON "public"."session_meta"("launchId" ASC);

-- CreateIndex
CREATE INDEX "session_meta_orgId_externalProvider_externalScopeId_idx" ON "public"."session_meta"("orgId" ASC, "externalProvider" ASC, "externalScopeId" ASC);

-- CreateIndex
CREATE INDEX "session_meta_org_visibility_page_idx" ON "public"."session_meta"("orgId" ASC, "visibility" ASC, "lastActivityAt" DESC, "startedAt" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "session_meta_parentSessionId_idx" ON "public"."session_meta"("parentSessionId" ASC);

-- CreateIndex
CREATE INDEX "session_spend_agentId_at_idx" ON "public"."session_spend"("agentId" ASC, "at" ASC);

-- CreateIndex
CREATE INDEX "session_usage_agentId_lastActivityAt_idx" ON "public"."session_usage"("agentId" ASC, "lastActivityAt" ASC);

-- CreateIndex
CREATE INDEX "shared_thread_agent_botId_idx" ON "public"."shared_thread_agent"("botId" ASC);

-- CreateIndex
CREATE INDEX "shared_thread_participant_botId_idx" ON "public"."shared_thread_participant"("botId" ASC);

-- CreateIndex
CREATE INDEX "skill_source_orgId_idx" ON "public"."skill_source"("orgId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "skill_source_orgId_name_key" ON "public"."skill_source"("orgId" ASC, "name" ASC);

-- CreateIndex
CREATE INDEX "slack_install_createdAt_idx" ON "public"."slack_install"("createdAt" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "waitlist_entry_email_key" ON "public"."waitlist_entry"("email" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "waitlist_entry_tokenHash_key" ON "public"."waitlist_entry"("tokenHash" ASC);

-- CreateIndex
CREATE INDEX "webchat_conversation_agentId_idx" ON "public"."webchat_conversation"("agentId" ASC);

-- CreateIndex
CREATE INDEX "webchat_conversation_currentSessionId_idx" ON "public"."webchat_conversation"("currentSessionId" ASC);

-- CreateIndex
CREATE INDEX "webchat_conversation_orgId_idx" ON "public"."webchat_conversation"("orgId" ASC);

-- CreateIndex
CREATE INDEX "webchat_conversation_userId_idx" ON "public"."webchat_conversation"("userId" ASC);

-- CreateIndex
CREATE INDEX "webchat_conversation_agent_agentId_idx" ON "public"."webchat_conversation_agent"("agentId" ASC);

-- CreateIndex
CREATE INDEX "webchat_conversation_agent_currentSessionId_idx" ON "public"."webchat_conversation_agent"("currentSessionId" ASC);

-- CreateIndex
CREATE INDEX "webchat_mcp_access_grant_authorityId_status_idx" ON "public"."webchat_mcp_access_grant"("authorityId" ASC, "status" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "webchat_mcp_access_grant_descriptorInstanceId_grantRevision_key" ON "public"."webchat_mcp_access_grant"("descriptorInstanceId" ASC, "grantRevision" ASC);

-- CreateIndex
CREATE INDEX "webchat_mcp_access_grant_descriptorInstanceId_status_idx" ON "public"."webchat_mcp_access_grant"("descriptorInstanceId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "webchat_mcp_access_grant_status_expiresAt_idx" ON "public"."webchat_mcp_access_grant"("status" ASC, "expiresAt" ASC);

-- CreateIndex
CREATE INDEX "webchat_mcp_access_grant_status_pendingExpiresAt_idx" ON "public"."webchat_mcp_access_grant"("status" ASC, "pendingExpiresAt" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "webchat_mcp_access_grant_tokenHash_key" ON "public"."webchat_mcp_access_grant"("tokenHash" ASC);

-- CreateIndex
CREATE INDEX "webchat_mcp_delegation_agentId_revokedAt_idx" ON "public"."webchat_mcp_delegation"("agentId" ASC, "revokedAt" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "webchat_mcp_delegation_conversationId_generation_key" ON "public"."webchat_mcp_delegation"("conversationId" ASC, "generation" ASC);

-- CreateIndex
CREATE INDEX "webchat_mcp_delegation_conversationId_revokedAt_idx" ON "public"."webchat_mcp_delegation"("conversationId" ASC, "revokedAt" ASC);

-- CreateIndex
CREATE INDEX "webchat_mcp_delegation_expiresAt_idx" ON "public"."webchat_mcp_delegation"("expiresAt" ASC);

-- CreateIndex
CREATE INDEX "webchat_mcp_operation_conversation_status_created_idx" ON "public"."webchat_mcp_operation"("conversationId" ASC, "status" ASC, "createdAt" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "webchat_mcp_operation_open_intent_key" ON "public"."webchat_mcp_operation"("conversationId" ASC, "intentHash" ASC)
WHERE "status" = 'awaiting_confirmation';

-- CreateIndex
CREATE INDEX "webchat_mcp_operation_status_recovery_idx" ON "public"."webchat_mcp_operation"("status" ASC, "recoveryDeadline" ASC, "id" ASC);

-- CreateIndex
CREATE INDEX "webchat_mcp_transport_receipt_grant_created_idx" ON "public"."webchat_mcp_transport_receipt"("grantId" ASC, "createdAt" ASC);

-- CreateIndex
CREATE INDEX "webchat_mcp_transport_receipt_operation_idx" ON "public"."webchat_mcp_transport_receipt"("operationId" ASC);

-- CreateIndex
CREATE INDEX "organization_knowledge_revision_search_idx"
ON "public"."organization_knowledge_revision"
USING GIN (to_tsvector('simple', COALESCE("content", '') || ' ' || COALESCE("summary", '')));

-- AddForeignKey
ALTER TABLE "public"."agent" ADD CONSTRAINT "agent_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."agent" ADD CONSTRAINT "agent_daemonId_fkey" FOREIGN KEY ("daemonId") REFERENCES "public"."daemon"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."agent" ADD CONSTRAINT "agent_lastModifiedByUserId_fkey" FOREIGN KEY ("lastModifiedByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."agent" ADD CONSTRAINT "agent_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."agent_launch" ADD CONSTRAINT "agent_launch_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."agent_launch" ADD CONSTRAINT "agent_launch_daemonId_fkey" FOREIGN KEY ("daemonId") REFERENCES "public"."daemon"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."agent_repo_authorization" ADD CONSTRAINT "agent_repo_authorization_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."agent_repo_authorization" ADD CONSTRAINT "agent_repo_authorization_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."agent_secret" ADD CONSTRAINT "agent_secret_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."api_key" ADD CONSTRAINT "api_key_daemonId_fkey" FOREIGN KEY ("daemonId") REFERENCES "public"."daemon"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."api_key" ADD CONSTRAINT "api_key_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."api_key" ADD CONSTRAINT "api_key_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."assignment" ADD CONSTRAINT "assignment_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."assignment" ADD CONSTRAINT "assignment_daemonId_fkey" FOREIGN KEY ("daemonId") REFERENCES "public"."daemon"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."bot" ADD CONSTRAINT "bot_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."bot" ADD CONSTRAINT "bot_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."bot_secret" ADD CONSTRAINT "bot_secret_botId_fkey" FOREIGN KEY ("botId") REFERENCES "public"."bot"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."cron_def" ADD CONSTRAINT "cron_def_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."cron_def" ADD CONSTRAINT "cron_def_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."cron_def" ADD CONSTRAINT "cron_def_lastModifiedByUserId_fkey" FOREIGN KEY ("lastModifiedByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."cron_def" ADD CONSTRAINT "cron_def_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."cron_def" ADD CONSTRAINT "cron_def_targetIntegrationId_fkey" FOREIGN KEY ("targetIntegrationId") REFERENCES "public"."integration"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."cron_run" ADD CONSTRAINT "cron_run_cronId_fkey" FOREIGN KEY ("cronId") REFERENCES "public"."cron_def"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."daemon" ADD CONSTRAINT "daemon_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."daemon" ADD CONSTRAINT "daemon_lastModifiedByUserId_fkey" FOREIGN KEY ("lastModifiedByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."daemon" ADD CONSTRAINT "daemon_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."daemon_lifecycle_op" ADD CONSTRAINT "daemon_lifecycle_op_daemonId_fkey" FOREIGN KEY ("daemonId") REFERENCES "public"."daemon"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."deployment_secret" ADD CONSTRAINT "deployment_secret_deploymentConfigId_fkey" FOREIGN KEY ("deploymentConfigId") REFERENCES "public"."deployment_config"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."external_memory_connection" ADD CONSTRAINT "external_memory_connection_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."external_memory_connection" ADD CONSTRAINT "external_memory_connection_installationId_fkey" FOREIGN KEY ("installationId") REFERENCES "public"."memory_plugin_installation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."external_memory_connection" ADD CONSTRAINT "external_memory_connection_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."external_memory_connection_secret" ADD CONSTRAINT "external_memory_connection_secret_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "public"."external_memory_connection"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."external_memory_grant" ADD CONSTRAINT "external_memory_grant_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "public"."external_memory_connection"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."external_scope" ADD CONSTRAINT "external_scope_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."github_installation" ADD CONSTRAINT "github_installation_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."hook_def" ADD CONSTRAINT "hook_def_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."hook_def" ADD CONSTRAINT "hook_def_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."hook_def" ADD CONSTRAINT "hook_def_lastModifiedByUserId_fkey" FOREIGN KEY ("lastModifiedByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."hook_def" ADD CONSTRAINT "hook_def_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."hook_def" ADD CONSTRAINT "hook_def_targetIntegrationId_fkey" FOREIGN KEY ("targetIntegrationId") REFERENCES "public"."integration"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."hook_review_subject" ADD CONSTRAINT "hook_review_subject_projectionId_fkey" FOREIGN KEY ("projectionId") REFERENCES "public"."hook_review_projection"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."hook_secret" ADD CONSTRAINT "hook_secret_hookId_fkey" FOREIGN KEY ("hookId") REFERENCES "public"."hook_def"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."integration" ADD CONSTRAINT "integration_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."integration" ADD CONSTRAINT "integration_botId_fkey" FOREIGN KEY ("botId") REFERENCES "public"."bot"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."integration" ADD CONSTRAINT "integration_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."integration" ADD CONSTRAINT "integration_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."integration_channel" ADD CONSTRAINT "integration_channel_integrationId_fkey" FOREIGN KEY ("integrationId") REFERENCES "public"."integration"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."managed_skill" ADD CONSTRAINT "managed_skill_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."managed_skill_revision" ADD CONSTRAINT "managed_skill_revision_managedSkillId_fkey" FOREIGN KEY ("managedSkillId") REFERENCES "public"."managed_skill"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."mcp_grant" ADD CONSTRAINT "mcp_grant_mcpProviderId_fkey" FOREIGN KEY ("mcpProviderId") REFERENCES "public"."mcp_provider"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."mcp_provider" ADD CONSTRAINT "mcp_provider_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."mcp_provider" ADD CONSTRAINT "mcp_provider_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."mcp_provider_secret" ADD CONSTRAINT "mcp_provider_secret_mcpProviderId_fkey" FOREIGN KEY ("mcpProviderId") REFERENCES "public"."mcp_provider"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."membership" ADD CONSTRAINT "membership_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."membership" ADD CONSTRAINT "membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."memory_plugin_installation" ADD CONSTRAINT "memory_plugin_installation_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."memory_plugin_installation" ADD CONSTRAINT "memory_plugin_installation_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."org_invite_link" ADD CONSTRAINT "org_invite_link_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."org_invite_link" ADD CONSTRAINT "org_invite_link_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."org_invite_redemption" ADD CONSTRAINT "org_invite_redemption_inviteLinkId_fkey" FOREIGN KEY ("inviteLinkId") REFERENCES "public"."org_invite_link"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."org_invite_redemption" ADD CONSTRAINT "org_invite_redemption_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."organization_environment_assignment" ADD CONSTRAINT "organization_environment_assignment_agentId_orgId_fkey" FOREIGN KEY ("agentId", "orgId") REFERENCES "public"."agent"("id", "orgId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."organization_environment_assignment" ADD CONSTRAINT "organization_environment_assignment_authorizedByUserId_fkey" FOREIGN KEY ("authorizedByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."organization_environment_assignment" ADD CONSTRAINT "organization_environment_assignment_entryId_orgId_fkey" FOREIGN KEY ("entryId", "orgId") REFERENCES "public"."organization_environment_entry"("id", "orgId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."organization_environment_entry" ADD CONSTRAINT "organization_environment_entry_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."organization_environment_entry" ADD CONSTRAINT "organization_environment_entry_lastModifiedByUserId_fkey" FOREIGN KEY ("lastModifiedByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."organization_environment_entry" ADD CONSTRAINT "organization_environment_entry_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."organization_environment_secret" ADD CONSTRAINT "organization_environment_secret_entryId_fkey" FOREIGN KEY ("entryId") REFERENCES "public"."organization_environment_entry"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."organization_knowledge" ADD CONSTRAINT "organization_knowledge_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."organization_knowledge_revision" ADD CONSTRAINT "organization_knowledge_revision_knowledgeId_fkey" FOREIGN KEY ("knowledgeId") REFERENCES "public"."organization_knowledge"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."organization_suggestion" ADD CONSTRAINT "organization_suggestion_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."preset_agent" ADD CONSTRAINT "preset_agent_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."preset_agent" ADD CONSTRAINT "preset_agent_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."runtime_profile" ADD CONSTRAINT "runtime_profile_daemonId_fkey" FOREIGN KEY ("daemonId") REFERENCES "public"."daemon"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."secret_lease" ADD CONSTRAINT "secret_lease_daemonId_fkey" FOREIGN KEY ("daemonId") REFERENCES "public"."daemon"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."session_external_access_policy" ADD CONSTRAINT "session_external_access_policy_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."session_meta" ADD CONSTRAINT "session_meta_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."session_meta" ADD CONSTRAINT "session_meta_daemonId_fkey" FOREIGN KEY ("daemonId") REFERENCES "public"."daemon"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."session_meta" ADD CONSTRAINT "session_meta_external_scope_fkey" FOREIGN KEY ("externalScopeId", "orgId", "externalProvider") REFERENCES "public"."external_scope"("id", "orgId", "provider") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "public"."session_meta" ADD CONSTRAINT "session_meta_launchId_fkey" FOREIGN KEY ("launchId") REFERENCES "public"."agent_launch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."session_spend" ADD CONSTRAINT "session_spend_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."session_usage" ADD CONSTRAINT "session_usage_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."skill_source" ADD CONSTRAINT "skill_source_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."app_user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."skill_source" ADD CONSTRAINT "skill_source_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."slack_user_config" ADD CONSTRAINT "slack_user_config_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."slack_user_config" ADD CONSTRAINT "slack_user_config_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_conversation" ADD CONSTRAINT "webchat_conversation_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_conversation" ADD CONSTRAINT "webchat_conversation_currentSessionId_fkey" FOREIGN KEY ("currentSessionId") REFERENCES "public"."session_meta"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_conversation" ADD CONSTRAINT "webchat_conversation_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_conversation" ADD CONSTRAINT "webchat_conversation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_conversation_agent" ADD CONSTRAINT "webchat_conversation_agent_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_conversation_agent" ADD CONSTRAINT "webchat_conversation_agent_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "public"."webchat_conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_conversation_agent" ADD CONSTRAINT "webchat_conversation_agent_currentSessionId_fkey" FOREIGN KEY ("currentSessionId") REFERENCES "public"."session_meta"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_mcp_access_grant" ADD CONSTRAINT "webchat_mcp_access_grant_authorityId_fkey" FOREIGN KEY ("authorityId") REFERENCES "public"."webchat_mcp_delegation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_mcp_delegation" ADD CONSTRAINT "webchat_mcp_delegation_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "public"."agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_mcp_delegation" ADD CONSTRAINT "webchat_mcp_delegation_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "public"."webchat_conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_mcp_delegation" ADD CONSTRAINT "webchat_mcp_delegation_daemonId_fkey" FOREIGN KEY ("daemonId") REFERENCES "public"."daemon"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_mcp_delegation" ADD CONSTRAINT "webchat_mcp_delegation_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_mcp_delegation" ADD CONSTRAINT "webchat_mcp_delegation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."app_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."webchat_mcp_operation" ADD CONSTRAINT "webchat_mcp_operation_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "public"."webchat_conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "public"."webchat_mcp_operation" ADD CONSTRAINT "webchat_mcp_operation_sourceGrantId_fkey" FOREIGN KEY ("sourceGrantId") REFERENCES "public"."webchat_mcp_access_grant"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "public"."webchat_mcp_transport_receipt" ADD CONSTRAINT "webchat_mcp_transport_receipt_grantId_fkey" FOREIGN KEY ("grantId") REFERENCES "public"."webchat_mcp_access_grant"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "public"."webchat_mcp_transport_receipt" ADD CONSTRAINT "webchat_mcp_transport_receipt_operationId_fkey" FOREIGN KEY ("operationId") REFERENCES "public"."webchat_mcp_operation"("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- PostgreSQL constraints and objects that Prisma's schema diff cannot represent.
ALTER TABLE "public"."agent"
ADD CONSTRAINT "agent_selected_audience_nonempty"
CHECK ("visibility" <> 'restricted'::"public"."ResourceVisibility" OR cardinality("sharedWith") > 0);

ALTER TABLE "public"."cron_def"
ADD CONSTRAINT "cron_def_selected_audience_nonempty"
CHECK ("visibility" <> 'restricted'::"public"."ResourceVisibility" OR cardinality("sharedWith") > 0);

ALTER TABLE "public"."daemon"
ADD CONSTRAINT "daemon_selected_audience_nonempty"
CHECK ("visibility" <> 'restricted'::"public"."ResourceVisibility" OR cardinality("sharedWith") > 0);

ALTER TABLE "public"."deployment_config"
ADD CONSTRAINT "deployment_config_revision_check" CHECK ("revision" > 0),
ADD CONSTRAINT "deployment_config_schema_version_check" CHECK ("schemaVersion" > 0),
ADD CONSTRAINT "deployment_config_singleton_check" CHECK ("id" = 1);

ALTER TABLE "public"."external_memory_connection"
ADD CONSTRAINT "external_memory_connection_config_check"
CHECK (jsonb_typeof("config") = 'object'),
ADD CONSTRAINT "external_memory_connection_revision_check"
CHECK (
  "revision" >= 1
  AND (
    "probedRevision" IS NULL
    OR ("probedRevision" >= 1 AND "probedRevision" <= "revision")
  )
);

ALTER TABLE "public"."external_memory_connection_secret"
ADD CONSTRAINT "external_memory_connection_secret_values_check"
CHECK (jsonb_typeof("values") = 'object');

ALTER TABLE "public"."external_memory_grant"
ADD CONSTRAINT "external_memory_grant_status_check"
CHECK ("status" IN ('active', 'revoked'));

ALTER TABLE "public"."managed_skill"
ADD CONSTRAINT "managed_skill_currentRevision_check" CHECK ("currentRevision" > 0);

ALTER TABLE "public"."managed_skill_revision"
ADD CONSTRAINT "managed_skill_revision_bounds_check"
CHECK (
  "revision" > 0
  AND "compressedBytes" BETWEEN 1 AND 524288
  AND "expandedBytes" BETWEEN 1 AND 4194304
  AND "fileCount" BETWEEN 1 AND 64
  AND octet_length("archive") = "compressedBytes"
),
ADD CONSTRAINT "managed_skill_revision_digest_check"
CHECK ("digest" ~ '^sha256:[0-9a-f]{64}$');

ALTER TABLE "public"."mcp_provider"
ADD CONSTRAINT "mcp_provider_selected_audience_nonempty"
CHECK ("visibility" <> 'restricted'::"public"."ResourceVisibility" OR cardinality("sharedWith") > 0);

ALTER TABLE "public"."memory_plugin_installation"
ADD CONSTRAINT "memory_plugin_installation_profile_major_check"
CHECK ("pinnedProfileMajor" = 1),
ADD CONSTRAINT "memory_plugin_installation_secret_headers_check"
CHECK (jsonb_typeof("secretHeaders") = 'array'),
ADD CONSTRAINT "memory_plugin_installation_transport_target_check"
CHECK (
  (
    "transport" = 'streamable_http'::"public"."MemoryPluginTransport"
    AND "endpoint" IS NOT NULL
    AND "commandRef" IS NULL
  )
  OR (
    "transport" = 'stdio'::"public"."MemoryPluginTransport"
    AND "endpoint" IS NULL
    AND "commandRef" IS NOT NULL
  )
);

ALTER TABLE "public"."organization_environment_entry"
ADD CONSTRAINT "organization_environment_entry_variable_value_check"
CHECK ("kind" = 'variable'::"public"."OrganizationEnvironmentKind" OR "variableValue" IS NULL),
ADD CONSTRAINT "organization_environment_entry_version_check"
CHECK ("version" > 0);

ALTER TABLE "public"."organization_knowledge"
ADD CONSTRAINT "organization_knowledge_currentRevision_check" CHECK ("currentRevision" > 0);

ALTER TABLE "public"."organization_knowledge_revision"
ADD CONSTRAINT "organization_knowledge_revision_digest_check"
CHECK ("digest" ~ '^sha256:[0-9a-f]{64}$'),
ADD CONSTRAINT "organization_knowledge_revision_revision_check"
CHECK ("revision" > 0);

ALTER TABLE "public"."organization_suggestion"
ADD CONSTRAINT "organization_suggestion_acceptance_check"
CHECK (
  ("acceptedArtifactId" IS NULL AND "acceptedArtifactRevision" IS NULL)
  OR ("acceptedArtifactId" IS NOT NULL AND "acceptedArtifactRevision" > 0)
),
ADD CONSTRAINT "organization_suggestion_content_check"
CHECK (
  "contentBytes" BETWEEN 1 AND 4194304
  AND cardinality("sessionIds") > 0
  AND "digest" ~ '^sha256:[0-9a-f]{64}$'
),
ADD CONSTRAINT "organization_suggestion_state_check"
CHECK (
  (
    "state" = 'pending'::"public"."OrganizationSuggestionState"
    AND "reviewedAt" IS NULL
    AND "acceptedArtifactId" IS NULL
  )
  OR (
    "state" = 'rejected'::"public"."OrganizationSuggestionState"
    AND "reviewedAt" IS NOT NULL
    AND "acceptedArtifactId" IS NULL
  )
  OR (
    "state" = 'accepted'::"public"."OrganizationSuggestionState"
    AND "reviewedAt" IS NOT NULL
    AND "acceptedArtifactId" IS NOT NULL
  )
),
ADD CONSTRAINT "organization_suggestion_target_check"
CHECK (
  (
    "operation" = 'create'::"public"."OrganizationSuggestionOperation"
    AND "targetArtifactId" IS NULL
    AND "targetRevision" IS NULL
  )
  OR (
    "operation" = 'update'::"public"."OrganizationSuggestionOperation"
    AND "targetArtifactId" IS NOT NULL
    AND "targetRevision" > 0
  )
);

ALTER TABLE "public"."session_meta"
ADD CONSTRAINT "session_meta_external_shape_check"
CHECK (
  (
    "externalProvider" IS NULL
    AND "externalScopeId" IS NULL
    AND "externalResolution" IS NULL
    AND "classifiedPolicyRev" IS NULL
    AND "visibility" <> 'external'::"public"."SessionVisibility"
  )
  OR (
    "externalProvider" IS NOT NULL
    AND "externalResolution" IS NOT NULL
    AND "classifiedPolicyRev" IS NOT NULL
    AND (
      "externalResolution" <> 'settled'::"public"."ExternalResolution"
      OR "externalScopeId" IS NOT NULL
    )
  )
);

ALTER TABLE "public"."skill_source"
ADD CONSTRAINT "skill_source_selected_audience_nonempty"
CHECK ("visibility" <> 'restricted'::"public"."ResourceVisibility" OR cardinality("sharedWith") > 0);

CREATE FUNCTION "public"."record_deleted_identity"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD."oidcSubject" IS NOT NULL THEN
    INSERT INTO "deleted_identity_cutoff" ("oidcSubject", "cutoffAt", "expiresAt")
    VALUES (OLD."oidcSubject", now(), now() + interval '24 hours')
    ON CONFLICT ("oidcSubject") DO UPDATE SET
      "cutoffAt"  = GREATEST("deleted_identity_cutoff"."cutoffAt", EXCLUDED."cutoffAt"),
      "expiresAt" = GREATEST("deleted_identity_cutoff"."expiresAt", EXCLUDED."expiresAt");
  END IF;
  RETURN OLD;
END;
$$;

CREATE TRIGGER "app_user_record_deleted_identity"
AFTER DELETE ON "public"."app_user"
FOR EACH ROW EXECUTE FUNCTION "public"."record_deleted_identity"();

-- The optional waitlist admin role is provisioned out of band in owned environments.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'waitlist_admin') THEN
    GRANT SELECT ON "public"."waitlist_entry" TO "waitlist_admin";
    GRANT INSERT (
      "id", "email", "name", "status", "note", "source",
      "tokenHash", "displayTail", "joinExpiresAt", "revokedAt",
      "approvedByUserId", "approvedAt", "createdAt", "updatedAt"
    ) ON "public"."waitlist_entry" TO "waitlist_admin";
    GRANT UPDATE (
      "name", "status", "note", "source",
      "tokenHash", "displayTail", "joinExpiresAt", "revokedAt",
      "approvedByUserId", "approvedAt", "updatedAt"
    ) ON "public"."waitlist_entry" TO "waitlist_admin";
  END IF;
END
$$;
