import { createHash } from 'node:crypto'
import type {
  ManagedSkill,
  ManagedSkillRevision,
  OrganizationKnowledge,
  OrganizationKnowledgeRevision,
  OrganizationSuggestion
} from '../../generated/prisma/client.js'
import { Prisma } from '../../generated/prisma/client.js'
import type {
  AcceptOrganizationSuggestionResult,
  ManagedSkillRecord,
  ManagedSkillRevisionRecord,
  OrganizationArtifactProvenance,
  OrganizationKnowledgeRecord,
  OrganizationKnowledgeRepo,
  OrganizationKnowledgeRevisionRecord,
  OrganizationSuggestionRecord,
  OrganizationSuggestionState
} from '../ports.js'
import type { OrganizationSuggestionInfo } from '@agentconnect.md/protocol'
import { OrgId } from '../../domain/ids.js'
import { organizationSuggestionSnapshotToken } from '../../organization-knowledge/suggestion-snapshot.js'
import { withAmbientTx, type PrismaLike } from '../prisma.js'

type KnowledgeWithRevision = OrganizationKnowledge & { revisions: OrganizationKnowledgeRevision[] }
type SkillWithRevision = ManagedSkill & { revisions: ManagedSkillRevision[] }

function sha256(value: string | Uint8Array): string {
  return `sha256:${createHash('sha256').update(value).digest('hex')}`
}

/** Prisma's generated Bytes input requires an ArrayBuffer-backed view; make a
 * defensive copy so callers may supply Buffer/SharedArrayBuffer-backed views. */
function prismaBytes(value: Uint8Array): Uint8Array<ArrayBuffer> {
  const copy = new Uint8Array(value.byteLength)
  copy.set(value)
  return copy
}

function toKnowledgeRevision(row: OrganizationKnowledgeRevision): OrganizationKnowledgeRevisionRecord {
  return {
    knowledgeId: row.knowledgeId,
    revision: row.revision,
    content: row.content,
    summary: row.summary,
    tags: row.tags,
    digest: row.digest,
    source: row.source,
    sourceAgentId: row.sourceAgentId,
    sourceDreamId: row.sourceDreamId,
    sourceCandidateId: row.sourceCandidateId,
    sourceSessionIds: row.sourceSessionIds,
    createdByUserId: row.createdByUserId,
    reviewedByUserId: row.reviewedByUserId,
    createdAt: row.createdAt
  }
}

function toKnowledge(row: KnowledgeWithRevision): OrganizationKnowledgeRecord {
  const revision = row.revisions[0]
  if (!revision) throw new Error(`organization knowledge ${row.id} has no current revision`)
  return {
    id: row.id,
    orgId: OrgId(row.orgId),
    title: row.title,
    currentRevision: row.currentRevision,
    archivedAt: row.archivedAt,
    archivedByUserId: row.archivedByUserId,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    content: revision.content,
    summary: revision.summary,
    tags: revision.tags,
    digest: revision.digest,
    source: revision.source,
    sourceAgentId: revision.sourceAgentId,
    sourceDreamId: revision.sourceDreamId,
    sourceCandidateId: revision.sourceCandidateId,
    sourceSessionIds: revision.sourceSessionIds,
    createdByUserId: revision.createdByUserId,
    reviewedByUserId: revision.reviewedByUserId,
    revisionCreatedAt: revision.createdAt
  }
}

function toSkillRevision(row: ManagedSkillRevision): ManagedSkillRevisionRecord {
  return {
    managedSkillId: row.managedSkillId,
    revision: row.revision,
    archive: new Uint8Array(row.archive),
    digest: row.digest,
    compressedBytes: row.compressedBytes,
    expandedBytes: row.expandedBytes,
    fileCount: row.fileCount,
    manifest: row.manifest as Record<string, unknown>,
    source: row.source,
    sourceAgentId: row.sourceAgentId,
    sourceDreamId: row.sourceDreamId,
    sourceCandidateId: row.sourceCandidateId,
    sourceSessionIds: row.sourceSessionIds,
    createdByUserId: row.createdByUserId,
    reviewedByUserId: row.reviewedByUserId,
    createdAt: row.createdAt
  }
}

function toSkill(row: SkillWithRevision): ManagedSkillRecord {
  const revision = row.revisions[0]
  if (!revision) throw new Error(`managed skill ${row.id} has no current revision`)
  return {
    id: row.id,
    orgId: OrgId(row.orgId),
    name: row.name,
    description: row.description,
    currentRevision: row.currentRevision,
    archivedAt: row.archivedAt,
    archivedByUserId: row.archivedByUserId,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    digest: revision.digest,
    compressedBytes: revision.compressedBytes,
    expandedBytes: revision.expandedBytes,
    fileCount: revision.fileCount,
    manifest: revision.manifest as Record<string, unknown>
  }
}

function toSuggestion(row: OrganizationSuggestion): OrganizationSuggestionRecord {
  return {
    id: row.id,
    orgId: OrgId(row.orgId),
    sourceAgentId: row.sourceAgentId,
    sourceDaemonId: row.sourceDaemonId,
    dreamId: row.dreamId,
    candidateId: row.candidateId,
    kind: row.kind,
    operation: row.operation,
    targetArtifactId: row.targetArtifactId,
    targetRevision: row.targetRevision,
    title: row.title,
    summary: row.summary,
    tags: row.tags,
    digest: row.digest,
    contentBytes: row.contentBytes,
    sessionIds: row.sessionIds,
    state: row.state,
    reviewedByUserId: row.reviewedByUserId,
    reviewedAt: row.reviewedAt,
    reviewReason: row.reviewReason,
    acceptedArtifactId: row.acceptedArtifactId,
    acceptedArtifactRevision: row.acceptedArtifactRevision,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt
  }
}

function provenanceData(provenance: OrganizationArtifactProvenance) {
  return {
    source: provenance.source,
    sourceAgentId: provenance.sourceAgentId ?? null,
    sourceDreamId: provenance.sourceDreamId ?? null,
    sourceCandidateId: provenance.sourceCandidateId ?? null,
    sourceSessionIds: provenance.sourceSessionIds ?? [],
    createdByUserId: provenance.createdByUserId ?? null,
    reviewedByUserId: provenance.reviewedByUserId ?? null
  }
}

const currentKnowledgeInclude = {
  revisions: { orderBy: { revision: 'desc' as const }, take: 1 }
}

const currentSkillInclude = {
  revisions: { orderBy: { revision: 'desc' as const }, take: 1 }
}

export class PgOrganizationKnowledgeRepo implements OrganizationKnowledgeRepo {
  constructor(private readonly db: PrismaLike) {}

  async listKnowledge(orgId: OrgId, includeArchived = false): Promise<OrganizationKnowledgeRecord[]> {
    const rows = await this.db.organizationKnowledge.findMany({
      where: { orgId, ...(includeArchived ? {} : { archivedAt: null }) },
      include: currentKnowledgeInclude,
      orderBy: { updatedAt: 'desc' }
    })
    return rows.map(toKnowledge)
  }

  async getKnowledge(id: string): Promise<OrganizationKnowledgeRecord | null> {
    const row = await this.db.organizationKnowledge.findUnique({ where: { id }, include: currentKnowledgeInclude })
    return row ? toKnowledge(row) : null
  }

  async listKnowledgeRevisions(id: string): Promise<OrganizationKnowledgeRevisionRecord[]> {
    return (
      await this.db.organizationKnowledgeRevision.findMany({
        where: { knowledgeId: id },
        orderBy: { revision: 'desc' }
      })
    ).map(toKnowledgeRevision)
  }

  async searchKnowledge(
    orgId: OrgId,
    input: { query: string; tags?: string[]; limit: number }
  ): Promise<OrganizationKnowledgeRecord[]> {
    const query = input.query.trim()
    const like = `%${query}%`
    const tags = input.tags ?? []
    const rows = await this.db.$queryRaw<
      Array<
        OrganizationKnowledge & {
          content: string
          summary: string | null
          tags: string[]
          digest: string
          source: 'manual' | 'dream'
          sourceAgentId: string | null
          sourceDreamId: string | null
          sourceCandidateId: string | null
          sourceSessionIds: string[]
          createdByUserId: string | null
          reviewedByUserId: string | null
          revisionCreatedAt: Date
        }
      >
    >(Prisma.sql`
      SELECT k.*,
             r."content", r."summary", r."tags", r."digest", r."source",
             r."sourceAgentId", r."sourceDreamId", r."sourceCandidateId",
             r."sourceSessionIds", r."createdByUserId", r."reviewedByUserId",
             r."createdAt" AS "revisionCreatedAt"
      FROM "organization_knowledge" k
      JOIN "organization_knowledge_revision" r
        ON r."knowledgeId" = k."id" AND r."revision" = k."currentRevision"
      WHERE k."orgId" = ${orgId}
        AND k."archivedAt" IS NULL
        AND (${tags.length === 0} OR r."tags" @> ${tags}::text[])
        AND (
          k."title" ILIKE ${like}
          OR r."content" ILIKE ${like}
          OR coalesce(r."summary", '') ILIKE ${like}
          OR to_tsvector('simple', coalesce(r."content", '') || ' ' || coalesce(r."summary", ''))
             @@ websearch_to_tsquery('simple', ${query})
        )
      ORDER BY
        CASE WHEN lower(k."title") = lower(${query}) THEN 0
             WHEN k."title" ILIKE ${`${query}%`} THEN 1 ELSE 2 END,
        ts_rank(
          to_tsvector('simple', k."title" || ' ' || coalesce(r."summary", '') || ' ' || r."content"),
          websearch_to_tsquery('simple', ${query})
        ) DESC,
        k."updatedAt" DESC
      LIMIT ${input.limit}
    `)
    return rows.map((row) => ({
      id: row.id,
      orgId: OrgId(row.orgId),
      title: row.title,
      currentRevision: row.currentRevision,
      archivedAt: row.archivedAt,
      archivedByUserId: row.archivedByUserId,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
      content: row.content,
      summary: row.summary,
      tags: row.tags,
      digest: row.digest,
      source: row.source,
      sourceAgentId: row.sourceAgentId,
      sourceDreamId: row.sourceDreamId,
      sourceCandidateId: row.sourceCandidateId,
      sourceSessionIds: row.sourceSessionIds,
      createdByUserId: row.createdByUserId,
      reviewedByUserId: row.reviewedByUserId,
      revisionCreatedAt: row.revisionCreatedAt
    }))
  }

  async createKnowledge(
    orgId: OrgId,
    input: { title: string; content: string; summary?: string; tags?: string[] },
    provenance: OrganizationArtifactProvenance
  ): Promise<OrganizationKnowledgeRecord> {
    const row = await this.db.organizationKnowledge.create({
      data: {
        orgId,
        title: input.title,
        revisions: {
          create: {
            revision: 1,
            content: input.content,
            summary: input.summary ?? null,
            tags: input.tags ?? [],
            digest: sha256(input.content),
            ...provenanceData(provenance)
          }
        }
      },
      include: currentKnowledgeInclude
    })
    return toKnowledge(row)
  }

  async updateKnowledge(
    id: string,
    expectedRevision: number,
    input: { title: string; content: string; summary?: string; tags?: string[] },
    provenance: OrganizationArtifactProvenance
  ): Promise<OrganizationKnowledgeRecord | null> {
    return withAmbientTx(this.db, async (tx) => {
      const nextRevision = expectedRevision + 1
      const updated = await tx.organizationKnowledge.updateMany({
        where: { id, currentRevision: expectedRevision },
        data: { title: input.title, currentRevision: nextRevision }
      })
      if (updated.count === 0) return null
      await tx.organizationKnowledgeRevision.create({
        data: {
          knowledgeId: id,
          revision: nextRevision,
          content: input.content,
          summary: input.summary ?? null,
          tags: input.tags ?? [],
          digest: sha256(input.content),
          ...provenanceData(provenance)
        }
      })
      const row = await tx.organizationKnowledge.findUniqueOrThrow({ where: { id }, include: currentKnowledgeInclude })
      return toKnowledge(row)
    })
  }

  async setKnowledgeArchived(id: string, archived: boolean, byUserId?: string): Promise<OrganizationKnowledgeRecord> {
    const row = await this.db.organizationKnowledge.update({
      where: { id },
      data: archived
        ? { archivedAt: new Date(), archivedByUserId: byUserId ?? null }
        : { archivedAt: null, archivedByUserId: null },
      include: currentKnowledgeInclude
    })
    return toKnowledge(row)
  }

  async listManagedSkills(orgId: OrgId, includeArchived = false): Promise<ManagedSkillRecord[]> {
    return (
      await this.db.managedSkill.findMany({
        where: { orgId, ...(includeArchived ? {} : { archivedAt: null }) },
        include: currentSkillInclude,
        orderBy: { updatedAt: 'desc' }
      })
    ).map(toSkill)
  }

  async getManagedSkill(id: string): Promise<ManagedSkillRecord | null> {
    const row = await this.db.managedSkill.findUnique({ where: { id }, include: currentSkillInclude })
    return row ? toSkill(row) : null
  }

  async getManagedSkillRevision(id: string, revision: number): Promise<ManagedSkillRevisionRecord | null> {
    const row = await this.db.managedSkillRevision.findUnique({
      where: { managedSkillId_revision: { managedSkillId: id, revision } }
    })
    return row ? toSkillRevision(row) : null
  }

  async listManagedSkillRevisions(id: string): Promise<ManagedSkillRevisionRecord[]> {
    return (
      await this.db.managedSkillRevision.findMany({
        where: { managedSkillId: id },
        orderBy: { revision: 'desc' }
      })
    ).map(toSkillRevision)
  }

  async setManagedSkillArchived(id: string, archived: boolean, byUserId?: string): Promise<ManagedSkillRecord> {
    const row = await this.db.managedSkill.update({
      where: { id },
      data: archived
        ? { archivedAt: new Date(), archivedByUserId: byUserId ?? null }
        : { archivedAt: null, archivedByUserId: null },
      include: currentSkillInclude
    })
    return toSkill(row)
  }

  async syncSuggestions(
    orgId: OrgId,
    sourceDaemonId: string,
    suggestions: (OrganizationSuggestionInfo & { sourceAgentId: string; dreamId: string })[]
  ): Promise<OrganizationSuggestionRecord[]> {
    return withAmbientTx(this.db, async (tx) => {
      const records: OrganizationSuggestionRecord[] = []
      const ordered = [...suggestions].sort((left, right) => {
        const a = `${left.sourceAgentId}:${left.dreamId}:${left.candidateId}`
        const b = `${right.sourceAgentId}:${right.dreamId}:${right.candidateId}`
        return a < b ? -1 : a > b ? 1 : 0
      })
      for (const suggestion of ordered) {
        // A reconnect can overlap the connection it superseded. Serialize the
        // absent-row insert case by stable source identity, then row-lock an
        // existing candidate so an accept/reject transaction cannot race this
        // metadata refresh and have terminal fields overwritten afterward.
        const lockKey = `organization-suggestion:${suggestion.sourceAgentId}:${suggestion.dreamId}:${suggestion.candidateId}`
        // Prisma cannot deserialize PostgreSQL's `void` return type, so project
        // the lock call through a boolean expression (the same pattern used by
        // the other repository advisory locks).
        await tx.$queryRaw(
          Prisma.sql`SELECT pg_advisory_xact_lock(hashtextextended(${lockKey}, 0)) IS NULL AS "locked"`
        )
        await tx.$queryRaw(
          Prisma.sql`SELECT "id" FROM "organization_suggestion"
                     WHERE "sourceAgentId" = ${suggestion.sourceAgentId}::uuid
                       AND "dreamId" = ${suggestion.dreamId}
                       AND "candidateId" = ${suggestion.candidateId}::uuid
                     FOR UPDATE`
        )
        const key = {
          sourceAgentId_dreamId_candidateId: {
            sourceAgentId: suggestion.sourceAgentId,
            dreamId: suggestion.dreamId,
            candidateId: suggestion.candidateId
          }
        }
        const existing = await tx.organizationSuggestion.findUnique({ where: key })
        if (existing && existing.state !== 'pending') {
          records.push(toSuggestion(existing))
          continue
        }
        const data = {
          orgId,
          sourceAgentId: suggestion.sourceAgentId,
          sourceDaemonId,
          dreamId: suggestion.dreamId,
          candidateId: suggestion.candidateId,
          kind: suggestion.kind,
          operation: suggestion.operation,
          targetArtifactId: suggestion.targetId ?? null,
          targetRevision: suggestion.targetRevision ?? null,
          title: suggestion.title,
          summary: suggestion.summary ?? null,
          tags: suggestion.tags ?? [],
          digest: suggestion.digest,
          contentBytes: suggestion.contentBytes,
          sessionIds: suggestion.sessionIds,
          createdAt: new Date(suggestion.createdAt)
        }
        const row = existing
          ? await tx.organizationSuggestion.update({ where: { id: existing.id }, data })
          : await tx.organizationSuggestion.create({ data })
        records.push(toSuggestion(row))
      }
      return records
    })
  }

  async listSuggestions(
    orgId: OrgId,
    filters: { kind?: 'knowledge' | 'skill'; state?: OrganizationSuggestionState; query?: string } = {}
  ): Promise<OrganizationSuggestionRecord[]> {
    const query = filters.query?.trim()
    return (
      await this.db.organizationSuggestion.findMany({
        where: {
          orgId,
          ...(filters.kind ? { kind: filters.kind } : {}),
          ...(filters.state ? { state: filters.state } : {}),
          ...(query
            ? {
                OR: [
                  { title: { contains: query, mode: 'insensitive' as const } },
                  { summary: { contains: query, mode: 'insensitive' as const } }
                ]
              }
            : {})
        },
        orderBy: { createdAt: 'desc' },
        take: 200
      })
    ).map(toSuggestion)
  }

  async getSuggestion(id: string): Promise<OrganizationSuggestionRecord | null> {
    const row = await this.db.organizationSuggestion.findUnique({ where: { id } })
    return row ? toSuggestion(row) : null
  }

  async rejectSuggestion(
    id: string,
    reviewedByUserId: string | undefined,
    reason?: string
  ): Promise<OrganizationSuggestionRecord> {
    await this.db.organizationSuggestion.updateMany({
      where: { id, state: 'pending' },
      data: {
        state: 'rejected',
        reviewedByUserId: reviewedByUserId ?? null,
        reviewedAt: new Date(),
        reviewReason: reason ?? null
      }
    })
    return toSuggestion(await this.db.organizationSuggestion.findUniqueOrThrow({ where: { id } }))
  }

  async acceptKnowledgeSuggestion(
    id: string,
    body: { title: string; content: string; summary: string | null; tags: string[] },
    expectedSnapshotToken: string,
    reviewedByUserId?: string
  ): Promise<AcceptOrganizationSuggestionResult> {
    return withAmbientTx(this.db, async (tx) => {
      await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "organization_suggestion" WHERE "id" = ${id}::uuid FOR UPDATE`)
      const suggestion = await tx.organizationSuggestion.findUniqueOrThrow({ where: { id } })
      if (suggestion.state !== 'pending') return { outcome: 'not_pending', suggestion: toSuggestion(suggestion) }
      if (suggestion.kind !== 'knowledge') throw new Error('suggestion kind mismatch')
      if (organizationSuggestionSnapshotToken(toSuggestion(suggestion)) !== expectedSnapshotToken) {
        return { outcome: 'metadata_changed', suggestion: toSuggestion(suggestion) }
      }
      if (sha256(body.content) !== suggestion.digest) throw new Error('suggestion digest mismatch')
      if (
        suggestion.title !== body.title ||
        suggestion.summary !== body.summary ||
        JSON.stringify(suggestion.tags) !== JSON.stringify(body.tags)
      ) {
        return { outcome: 'metadata_changed', suggestion: toSuggestion(suggestion) }
      }

      let artifactId: string
      let revision: number
      if (suggestion.operation === 'create') {
        const created = await tx.organizationKnowledge.create({
          data: {
            orgId: suggestion.orgId,
            title: body.title,
            revisions: {
              create: {
                revision: 1,
                content: body.content,
                summary: body.summary,
                tags: body.tags,
                digest: suggestion.digest,
                source: 'dream',
                sourceAgentId: suggestion.sourceAgentId,
                sourceDreamId: suggestion.dreamId,
                sourceCandidateId: suggestion.candidateId,
                sourceSessionIds: suggestion.sessionIds,
                reviewedByUserId: reviewedByUserId ?? null
              }
            }
          }
        })
        artifactId = created.id
        revision = 1
      } else {
        if (!suggestion.targetArtifactId || !suggestion.targetRevision)
          return { outcome: 'target_missing', suggestion: toSuggestion(suggestion) }
        const target = await tx.organizationKnowledge.findFirst({
          where: { id: suggestion.targetArtifactId, orgId: suggestion.orgId, archivedAt: null }
        })
        if (!target) return { outcome: 'target_missing', suggestion: toSuggestion(suggestion) }
        if (target.currentRevision !== suggestion.targetRevision)
          return { outcome: 'stale_target', suggestion: toSuggestion(suggestion) }
        revision = target.currentRevision + 1
        const advanced = await tx.organizationKnowledge.updateMany({
          where: { id: target.id, currentRevision: target.currentRevision, archivedAt: null },
          data: { title: body.title, currentRevision: revision }
        })
        if (advanced.count === 0) return { outcome: 'stale_target', suggestion: toSuggestion(suggestion) }
        await tx.organizationKnowledgeRevision.create({
          data: {
            knowledgeId: target.id,
            revision,
            content: body.content,
            summary: body.summary,
            tags: body.tags,
            digest: suggestion.digest,
            source: 'dream',
            sourceAgentId: suggestion.sourceAgentId,
            sourceDreamId: suggestion.dreamId,
            sourceCandidateId: suggestion.candidateId,
            sourceSessionIds: suggestion.sessionIds,
            reviewedByUserId: reviewedByUserId ?? null
          }
        })
        artifactId = target.id
      }

      const accepted = await tx.organizationSuggestion.update({
        where: { id },
        data: {
          state: 'accepted',
          reviewedByUserId: reviewedByUserId ?? null,
          reviewedAt: new Date(),
          acceptedArtifactId: artifactId,
          acceptedArtifactRevision: revision
        }
      })
      return { outcome: 'accepted', suggestion: toSuggestion(accepted) }
    })
  }

  async acceptSkillSuggestion(
    id: string,
    body: {
      archive: Uint8Array
      candidateDigest: string
      digest: string
      compressedBytes: number
      expandedBytes: number
      fileCount: number
      manifest: Record<string, unknown>
      name: string
      description: string
    },
    expectedSnapshotToken: string,
    reviewedByUserId?: string
  ): Promise<AcceptOrganizationSuggestionResult> {
    try {
      return await withAmbientTx(this.db, async (tx) => {
        await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "organization_suggestion" WHERE "id" = ${id}::uuid FOR UPDATE`)
        const suggestion = await tx.organizationSuggestion.findUniqueOrThrow({ where: { id } })
        if (suggestion.state !== 'pending') return { outcome: 'not_pending', suggestion: toSuggestion(suggestion) }
        if (suggestion.kind !== 'skill') throw new Error('suggestion kind mismatch')
        if (organizationSuggestionSnapshotToken(toSuggestion(suggestion)) !== expectedSnapshotToken) {
          return { outcome: 'metadata_changed', suggestion: toSuggestion(suggestion) }
        }
        if (body.candidateDigest !== suggestion.digest || sha256(body.archive) !== body.digest)
          throw new Error('suggestion digest mismatch')
        if (suggestion.title !== body.name || suggestion.summary !== body.description) {
          return { outcome: 'metadata_changed', suggestion: toSuggestion(suggestion) }
        }

        let artifactId: string
        let revision: number
        if (suggestion.operation === 'create') {
          const created = await tx.managedSkill.create({
            data: {
              orgId: suggestion.orgId,
              name: body.name,
              description: body.description,
              revisions: {
                create: {
                  revision: 1,
                  archive: prismaBytes(body.archive),
                  digest: body.digest,
                  compressedBytes: body.compressedBytes,
                  expandedBytes: body.expandedBytes,
                  fileCount: body.fileCount,
                  manifest: body.manifest as Prisma.InputJsonValue,
                  source: 'dream',
                  sourceAgentId: suggestion.sourceAgentId,
                  sourceDreamId: suggestion.dreamId,
                  sourceCandidateId: suggestion.candidateId,
                  sourceSessionIds: suggestion.sessionIds,
                  reviewedByUserId: reviewedByUserId ?? null
                }
              }
            }
          })
          artifactId = created.id
          revision = 1
        } else {
          if (!suggestion.targetArtifactId || !suggestion.targetRevision)
            return { outcome: 'target_missing', suggestion: toSuggestion(suggestion) }
          const target = await tx.managedSkill.findFirst({
            where: { id: suggestion.targetArtifactId, orgId: suggestion.orgId, archivedAt: null }
          })
          if (!target) return { outcome: 'target_missing', suggestion: toSuggestion(suggestion) }
          if (target.currentRevision !== suggestion.targetRevision)
            return { outcome: 'stale_target', suggestion: toSuggestion(suggestion) }
          revision = target.currentRevision + 1
          const advanced = await tx.managedSkill.updateMany({
            where: { id: target.id, currentRevision: target.currentRevision, archivedAt: null },
            data: { name: body.name, description: body.description, currentRevision: revision }
          })
          if (advanced.count === 0) return { outcome: 'stale_target', suggestion: toSuggestion(suggestion) }
          await tx.managedSkillRevision.create({
            data: {
              managedSkillId: target.id,
              revision,
              archive: prismaBytes(body.archive),
              digest: body.digest,
              compressedBytes: body.compressedBytes,
              expandedBytes: body.expandedBytes,
              fileCount: body.fileCount,
              manifest: body.manifest as Prisma.InputJsonValue,
              source: 'dream',
              sourceAgentId: suggestion.sourceAgentId,
              sourceDreamId: suggestion.dreamId,
              sourceCandidateId: suggestion.candidateId,
              sourceSessionIds: suggestion.sessionIds,
              reviewedByUserId: reviewedByUserId ?? null
            }
          })
          artifactId = target.id
        }

        const accepted = await tx.organizationSuggestion.update({
          where: { id },
          data: {
            state: 'accepted',
            reviewedByUserId: reviewedByUserId ?? null,
            reviewedAt: new Date(),
            acceptedArtifactId: artifactId,
            acceptedArtifactRevision: revision
          }
        })
        return { outcome: 'accepted', suggestion: toSuggestion(accepted) }
      })
    } catch (err) {
      if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === 'P2002') {
        const suggestion = await this.getSuggestion(id)
        if (!suggestion) throw err
        return { outcome: 'name_conflict', suggestion }
      }
      throw err
    }
  }
}
